import scrapy

class spider1(scrapy.Spider):
    name = "spider1"
    domain = "https://angel.co/search?q="
    company_list = ['NatWest Group', 'Amdocs', 'U & V Consulting Group', 'Sunlight', 'Hire Digital', 'LimeTray', 'Lovebird Lingerie',
     'WIOAI', 'GokuKom Digital Agency', 'Tata Consultancy Services', 'Sheeko', 'Logicsofts Solutions Ltd', 'Junio',
     'Hike', 'ClickPost', 'magicpin', 'Kivi Capital', 'GyanDhan', 'Boston Scientific', 'Barclays', 'Appwharf', 'Sogeti',
     'Probus Smart Things', 'Bold Business', 'Electric Sheep Robotics', 'American Express Global Business Travel',
     'Sentieo', 'The Digital Divide', '360 Digital Idea', 'Tranzol', 'GreyNodes', 'Iresh7 Consulting',
     'DeepSpace9 Technologies', 'Swiggy', 'ThrivePass', 'TransUnion', 'USTRAA : Grooming For Men',
     'Black Riders Production LLP', 'ITCO Solutions, Inc.', 'Cubic Corporation', 'UNOPS', 'EXPERTIZ', 'Microsoft',
     'Personnel Selexions - Executive Search & Selection', 'Leena AI', 'UpGuard', 'Shelby Management Solutions', 'CDAC',
     'TECIE', 'Dimagi', 'A.P.T. Portfolio Private Limited', 'MGC Global Risk Advisory LLP', 'WhologicLife', 'VMware',
     'Red Hat', 'Sarvacharya Information Technology Private Limited', 'BONDS INDIA', 'Taxmann', 'Bechtel Corporation',
     'Unicorn Denmart Ltd.', 'StashFin', 'IBM', 'Logicsoft - Beyond Hype', 'StatusNeo', 'Gemini Solutions Pvt Ltd',
     'B.S.B. INTERNATIONAL CAREER PVT.  LTD', 'Hindustan Glass Works Limited', 'Kyndryl', 'Clarivate',
     'SrinSoft Technologies', 'Infinity Solutions', 'SabPaisa', 'Iris Software Inc.', 'TalentPret',
     'Right Infotech Solutions', 'TridIndia IT Translation Services Pvt.Ltd', 'CashKaro.com', 'Shift2Digital',
     'Trendzup Media', 'WorkSure MedPharma Consultancy India Pvt. Ltd.', 'Link Logistic Group', 'Grapes Digital',
     'Market Xcel Data Matrix Pvt. Ltd.', 'The Loom', 'OroPocket', 'Semco Infratech Pvt Ltd',
     'Viva Books Private Limited', 'Campfire Graphic Novels', 'Unacademy', 'Living Secrets (Brand : Vedic Charya)',
     'Flyshop.in', 'Blue Frog India', 'Paytm', 'Octopus & Jam Digital', 'Watermelon',
     'Alpine Modular Interiors Pvt Ltd', 'Sleeping Monkey', 'PhysicsWallah', 'Biztoast', 'Bigsmall.in', 'Simulanis',
     'Vidyam Tutorials', 'Bifrost Studios Pvt. Ltd.', 'Films Rajendraa', 'Codeyiizen Software & Services Pvt Ltd.',
     'Make My Business Online', 'Digitally Next', 'MX Player', 'Healthmug', 'NATBOT Lifestyles Pvt. Ltd.', 'Rozana.in',
     'Culminating Technologies (P) Ltd', 'Webgross', 'Accenture in India', 'Interactive Bees', 'Nature Morte',
     'BharatPe', 'VizExperts', 'Petrichor Health Care', 'The Financialist', 'Baazi Games', 'Socialize India', 'Monkhub',
     'Blu Cliff', 'Bajo Tierra (Premium Surfaces)', 'Aid On', 'Sportstech Brands Holding GmbH', 'Getz Destinations',
     'Onemark Media', 'Red Apple Technologies Pvt. Ltd.', 'Startxlabs Technologies', 'Boult Audio',
     'Uncap Research Labs', 'Abhiwan Technology', 'Shahnawaz (Pvt.) Limited', 'Jet Point Placement',
     'Innovation Technologies', 'IoTfy', 'HLK Infrastructure pvt ltd', 'Offcom Systems Pvt. Ltd.',
     'Alertus Technologies', 'J Mitra & Co Pvt Ltd', 'SEW-EURODRIVE India Private Limited',
     'NKG Infrastructure Limited', 'Capital Placement Services Gurgaon .', 'Midas Enterprises - India',
     'ServiTech Infra', 'Ashiana Homes', 'Reliance Jio Infocom Limited', 'KD Group of Industries',
     'All-State Electrical', 'SIS, LLC', 'GREEN IT Das Systemhaus GmbH',
     'Indo Asia Global Technologies Private Limited', 'Neo4j', 'Dell Technologies',
     'EduPristine Neev Knowledge Management Private Limited', 'Telamon HR Solutions', 'Excitel Broadband',
     'Palo Alto Networks', 'Genpact', 'Ubiquiti Inc.', 'ilabz Technology', 'Parakh Online Pvt. Ltd.', 'Chegg Inc.',
     'Computer Ware India Private Limited', 'SR Expert Services', 'Proactive Data Systems Pvt. Ltd.', 'Forrester',
     'Alfobit', 'LawSikho', 'SAGUNA CONSULTING SERVICES LLC', 'Bain & Company', 'Wipro', 'Consilium Software',
     'Vinfinity Immigration LLP', 'Roche', 'Development Alternatives', 'CaaStle', 'Panamax Infotech', 'bijnis',
     'Knowbiliti', 'Zuhouz', 'Endovision', 'Magic Billion', 'Xencov', 'FARFETCH', 'Equifax',
     'Revolute Soft Solution Pvt. Ltd.', 'Alpha Six Capital', '1K Kirana Bazaar', 'Niswey', 'Agoda', 'Vinsol',
     'Accedo.tv', 'Ogmen Robotics', 'indianfertilizer', 'Credflow', 'Triny', 'IT Company', 'Aeroprime Group',
     'IncuPad India Pvt Ltd', 'PureSoftware Ltd', 'Savatarr', 'Lendbox', 'ESOISC  International', 'Insight', 'Bijak',
     'Sanguine Technologies Pvt. Ltd.', 'ShipBob, Inc.', 'Optum', 'SalaryBox', 'Liberin Technologies',
     'Factech Solutions', 'Metaweb Technologies Pvt. Ltd.', 'Crossover for Work', 'Amazon Web Services (AWS)',
     'Saviance Technologies', 'Quincus', 'Team Computers', 'TOTL RPO SOLUTIONS LLP', 'Safe Security',
     'VSN International', 'Emeritus', 'UnitedHealth Group', 'Zedsoftpoint', 'Nykaa',
     'National Institute for Smart Government', 'Wadhwani Foundation', 'WK Associates LLP', 'Michael Page',
     'Reynold Infotek', 'Best Infosystems Ltd.', "Children's Investment Fund Foundation (CIFF)", 'MediagraphixPR',
     'VAMedia Box Pvt. Ltd.', 'TheStoryPedia', 'Wabbitfree', 'There for you', 'DPI Infotech', 'Modus Create',
     'Whiz Advert', 'REVE Systems', 'Arihant Publications India Limited', 'BlueOptima', 'Outdoor Adventure Camp',
     'Noosyn Tech', 'EyeMantra Foundation', 'Merino Consulting Services', 'TradebooX', 'TheCodeKnot', 'Squareboat',
     'The RapidPill', 'Learnin', 'RocketTech.in', 'LifeWorks', 'Bhartia Management Consultancy', 'Synopsys Inc',
     'StoreHippo', 'Cranberry Communications', 'ManpraX Software LLP', 'TCG Media Limited',
     'House Of Diagnostics - HOD', 'Easy To Pitch�', 'Foreignerds Inc.',
     'Webindia Master: SEO Company Delhi India, SEO Agency in Noida Delhi, SEO Services in Delhi India',
     'Red Dash Media', 'eMaven Solutions Pvt. Ltd.', 'Brand Provoke', 'Sohung Infotech', 'NMG Technologies',
     'SysTools Software Pvt Ltd', 'iSearch Solution Pvt. Ltd.', 'Gtechwebindia', 'KITINFINET', 'Global Trendz',
     'Paridhi Web Tech', 'NextraOne', 'Smartech Interactive Pvt Ltd', 'Astech Media Pvt Ltd', 'SunTec India',
     'Web Emporium', 'Nine Digital', 'Brand Liaison', 'Global IT Technology', 'Cog Culture Agency',
     'Synergy Web Designer', 'ClickLocal Digital Advertising LLP', 'Varya Vega Info Services Pvt. Ltd.', 'Full Circus',
     'Saatvik Communication', 'Dignitas Digital', 'Adaan Digital Solutions Pvt. Ltd.', 'LeagueSX', 'HcoRealEstates',
     'Cootz', 'MACBEE Pvt. Ltd.', 'TabletShablet', 'Jobs Ka Adda', 'Arramton Infotech Pvt. Ltd.', 'HT Media Ltd',
     'Centre for Digital Financial Inclusion, CDFI', 'Touchwood entertainment ltd', 'Smartechedu',
     'SecNinjaz Technologies LLP', 'MADE EASY PRIME', 'Laysan Technologies Pvt Ltd', 'Light Tree Ventures Group',
     'Glu Studios', 'Industrybuying.com', 'WORLDWIDE IMPRESSIVE & COMPETITIVE TECHNOLOGY SERVICES',
     'Anantha CyberTech Private Limited', 'PerkinElmer, Inc.', 'RALKEN Consultants & Construction',
     'DSV - Global Transport and Logistics', 'GD Goenka Public School, Sector-22, Rohini', 'Esri India',
     'Orbit Techsol', 'VBE Services INC', 'Bureau Veritas Group', 'Esri', 'VIKAS INFO SOLUTIONS PRIVATE LIMITED',
     'The Support Zone', 'Cod', 'MarvyLogic', 'Barclays Investment Bank', 'Mahajan Imaging', 'Valiance Solutions',
     'Xpat Consulting', 'HT Digital Streams', 'Textrics', 'MyMoneyMantra', 'Analytos', 'ARNOWA',
     'Datahub Technologies R&D PVT LTD', 'Hot Tub Condos', 'Collotech Inc', 'Econolytics', 'Octro Inc.', 'WinZO',
     'Apparrant Technologies', 'jellybean', 'Sparklin', 'ShipsKart', 'BlueNetvista', 'Classplus',
     'Webninjaz Technologies Pvt. Ltd.', 'Naukri.com', 'Fyp', 'frog', 'WFWA', 'Think Design Collaborative',
     'Milkbasket', 'Travvir', 'ECHO India', 'Adobe', 'Animal', 'Fella Homes', 'Blackcoffer', 'Guruji Astro',
     'Instahyre', 'Maximus Human Resources Pvt Ltd.', 'M�ngata Research', 'Extramarks Education India Pvt. Ltd.',
     'Orbis HR Solutions', 'Ucorn Group Pvt. Ltd.', 'GrowthGear', 'Websharpindia', 'LEAD School', 'Shiprocket',
     'Crownstack', 'TrueTech Solutions', 'I SQUARE SOFT', 'Boston Consulting Group (BCG)', 'SkyOnn Technologies',
     'Cynosure Corporate Solutions', 'MOURI Tech', 'Gap Inc.', 'Oracle', 'CarDekho', 'Salesforce',
     'CCS COMPUTERS PRIVATE LIMITED', 'SCA Technologies', 'Axtria - Ingenious Insights', 'Delhi University', 'VarSigma',
     'ASQ - World Headquarters', 'Apparel Resources', 'Climate Policy Initiative', 'Coding Ninjas', 'Inc42 Media',
     'Digital Green', 'Known', 'VCCircle', 'Invest India', 'Synergy Consulting, Inc.', 'Sequoia India', 'Coding Club',
     'International Initiative for Impact Evaluation (3ie)', 'Hacking Articles', 'Centre for Policy Research',
     'International Center for Research on Women (ICRW)', 'Global Health Strategies', 'Nishith Desai Associates',
     'IDinsight', 'SMS-Magic', 'Bahrain Economic Development Board (EDB)', 'Softcrylic', 'M&C Saatchi Performance',
     'CertOcean', 'Entrepreneur India', 'Elucidata', 'CertHippo Solution LLC', 'Phoenix Legal', 'CODLEO',
     'ScoopWhoop Media Pvt. Ltd.', 'Metro Rail News', 'Maven Workforce', 'Oxfam India', 'Hay House, Inc.',
     'Observer Research Foundation', 'Career Launcher', 'ThePrint', 'Projects Today India',
     'Campus-Corporate | Internship | Job Opportunities | Part-Time Jobs | Digital Marketing ', 'TravClan', 'LiveMint',
     'QSS Global', 'Hemp Foundation', 'Gallagher & Mohan', 'Hotel Jobs | JobKing.org', 'Job Alert', 'The Hacker News',
     'All Active Jobs', 'Internship / Job For Freshers', 'Sustainable Development Solutions Network',
     'Recruiting Cell | Indian Careers | Indian Jobs', 'Bar & Bench', 'Find My New Job',
     'Erekrut... Recruitment Made Easy', 'Coding Blocks', 'Growth Central VC', 'Pharmaceutical Guidelines',
     'Freshers Jobs', 'Freshers Camp', 'Qontento', 'Level AI', 'GTechLearn', 'Logistics Insider', 'Coursenator ',
     'Job Vacancy Result (official)', 'ACCEL HUMAN RESOURCE CONSULTANTS', 'CONSTRUCTION CANON',
     'Smriti Gupta LinkCvRight', 'CyberSecurity Jobs', 'PharmaState.academy ', 'Vahura', 'Career Expertoz', 'Alphaa AI',
     'Global Governance Initiative', 'Samagra | Transforming Governance', 'Whizlabs', 'Mercury Capital Advisors',
     'JobsGulf', 'KNR Management Consultants ', 'Centre for Civil Society', 'Vengreso | Prospect Better. Sell More.',
     'FranchiseBazar', 'Equalize Health', 'Nutrabay', 'Dare2Compete', 'DeservingJob',
     'PD Consulting Engineers Pvt. Ltd.', 'Digital Marketing Google Certification', 'Magnificent Bharat',
     'Mulya Technologies', 'CAclubindia', 'Intel Corporation', 'The Midtown Group', 'Medi-Lynx Cardiac Monitoring, LLC',
     'Negotiatus', 'Procter & Gamble', 'Amtraco, Inc.', 'Ikonix USA', 'Ocean Network Express North America',
     'Remcom Inc.', 'Virginia Tire & Auto', 'Cognite', 'The Association for Frontotemporal Degeneration (AFTD)',
     'Experlogix, Inc.', 'Bandwidth Inc.', 'LEARN Behavioral', 'Skin Perfect Brothers', 'SpringbokIT',
     'QuadraNet Enterprises, LLC.', 'Leidos', 'Databricks', 'Experian', 'Next Move, Inc', 'FEMA', 'Conservation Legacy',
     'Ubisoft', 'Withum', 'SOLARPACK', 'Morphogenesis', 'HSE INTEGRO', 'Centre for Science and Environment, New Delhi',
     'BRBA AEROSPACE PVT LTD', 'ACURA SOLUTIONS LTD', 'AiBorne Tech', 'Fresher Openings',
     'Indian Private Equity & Venture Capital Association (IVCA)', 'InternToJob - Internships & Dream Jobs',
     'ModernVacancy | Hospitality Jobs', 'The Rasich Group (TRG)', 'InternHelp', 'Naukri Catcher', 'Full Stack Squad',
     'Rail Analysis - Insights', 'MBA Shots', 'Umeed India Foundation (UIF)', 'The Strategy Story',
     'Admantium Crypto Advisors', 'Indian Chemical News', 'EdMyst - The Talent Transformation Platform', 'NaukriA2Z',
     'Carnegie India', 'Indian Staffing Federation', 'Looking For Job', 'Govt Jobs & Tenders for CA/CS/CMA',
     'Grad Partners', 'KiKi Social', 'Qualicentric LLP', 'Webiance', 'Jobs & Hiring Updates (SeekaJob)',
     'CA CS CMA Jobs, Articleship & Industrial Training Vacancy', 'WaterBridge Ventures', 'Foodtech Simplified',
     'QUALITY CONTROL PROFESSIONALS', 'SKYLINE HR INTERNATIONAL (MEA LICENSE NO.: B-1366/DEL/PER/1000/5/9881/2021)',
     'HRKatha', 'Business Insider India', 'Natifi.ai', 'Adamant HR Consulting Pvt. Ltd.', 'Job News Academy',
     'SK - Human Resources Consultant', 'AudPop', 'The WallStreet School', 'Talkpush', 'Novistra Capital',
     'MadOverGames', 'Flexing It�', 'Anannda Foods and Beverages', 'AXA Consultants', 'Human Capital Magazine',
     'Precily, Inc.', 'Indian Angel Network', 'Internet and Mobile Association of India',
     'Global Cold Chain Alliance (GCCA)', 'LawBhoomi', 'Indian Startup News', 'RCi.Interio', 'Arthigamya',
     'My Content Cafe', 'Codigo Aldea', 'Theax', 'Mediklik', 'InAmigos Foundation', 'Chhattisgarh Rojgar',
     'Recruit Desk', 'Area 52', 'Bizolution Technologies Pvt Ltd ', 'Shivtensity�', 'Interestopedia', 'AlgoUniversity',
     'Digital Marketing Guru', 'AP Industry Conferences', 'NXG Solutions', 'my ARABPATI', 'Homelink Interior Design',
     'Renascence Marketing & Advertisement', 'AIC@36INC', 'Bigwigs India ', 'ClevrHyk', 'AST Jobs Provider',
     'Avasar.life', 'Progressive Constitutional Law Society - HNLU Chapter', 'Moggly India', 'KTINDU�TRIE�',
     'SarvSreStha Institute', 'First Estimates', 'StratAZy - Converting Ideas into StartUps.', 'Coders Troop',
     'Erkey Motors India Pvt. Ltd', 'Resilient Sustainance (RSustain)', 'BASICS Studio', 'WebCoodee',
     'Adivasi Lives Matter', 'The GenZY Course', '9incglobal', 'Google Developer Student Clubs, NIT Raipur',
     'Bright Job Consultancy', 'Inforob Automation', 'Anvy Technologies', 'Lores Legal', 'Webber ElectroCorp',
     'LAKSHYA CHARITABLE TRUST', 'IT Junkies', 'Augmentuss Automations LLP', 'Bayer', 'Nike', 'Ford M�xico',
     'BMW Brilliance Automotive', 'Petroplan', 'Lucid Motors', 'Listgrove Ltd', 'JetBlue', 'Collins Aerospace',
     'Under Armour', 'A*STAR - Agency for Science, Technology and Research', 'Etihad Rail DB', 'Black Diamond Networks',
     'Parsons Corporation', 'Nordstrom', 'Tayco', 'BLUE ORIGIN', "Chico's FAS, Inc.", 'amazon market',
     'MKF Finance Ltd', 'Bajaj Finserv', 'Cargill', 'Deeksha CA Academy', 'SPACE Consultants', '_Royal_', 'Atos',
     'Cardlytics', 'Cenerg Global Tools Pvt Ltd', 'West Pharmaceutical Services', 'TRIMEDX', 'Pfizer',
     'Foursis Technical Solutions', 'EVEREST PLY & VENEERS PRIVATE LIMITED', 'Uplers', 'EDGE SPACE SYSTEMS, INC.',
     'Peak Infrastructure Management Services Pvt. Ltd.', "Divi's Laboratories Limited",
     'TeamSpace Financial Services Pvt. Ltd.', 'Exide Life Insurance',
     'Grameena Vikas Kendram Society for Rural Development', 'Alliance Recruitment Agency', 'ACCA Careers',
     'Bajaj Allianz Life', 'Max Life Insurance Company Limited', 'SBI Life Insurance Co. Ltd.',
     'Prov HR Solutions Private Limited', 'logon.design', 'Diverse Lynx', 'autojhonny', 'Nitin Tiwari', 'TEKWISSEN �',
     'PhonePe', 'AVTEC Limited', 'Talent Acquisition Consultancy', 'Miracle Software Systems, Inc', 'NerdPine',
     'Greenpanel Industries Limited', 'Precisely | Trust in Data', 'SUPRO INFO SOLUTIONS PRIVATE LIMITED',
     'ARAVIND EYE CARE SYSTEM', 'Impulsum Creative Solutions Pvt. Ltd.', 'Andhra Medical College', 'Skillsoft',
     'KRISHNAAG ROCKS AND MINERALS LLP', 'Accounting Today', 'BMW KUN Exclusive Telangana & AP',
     'M&N MOTORS PRIVATE LIMITED', 'Questt', 'HeadPro Consulting LLP', 'Indiabulls Group', 'TransPerfect',
     'HITEX (Hyderabad International Trade Expositions Limited)', 'Muthoot Fincorp Ltd.', 'Grow Indigo Pvt. Ltd.',
     'Novotel Hotels', 'Fairfield Inn & Suites by Marriott', 'Vina Venkatesa Foods', 'Kotak Mahindra Bank',
     'Prakash Parcel Services Limited', 'Addnectar Solution', 'S. M. Niryat Private Limited', 'Care Insurance', 'Cipla',
     'Toppr', 'Edomotics Smart Systems (P) Ltd', 'Pruna Industries Private Limited', 'Bio Bodyfuelz Ltd',
     'Bharti Airtel', 'Bluetech Agro Pvt Ltd', 'Red Cat Technology India Pvt. Ltd.', 'Bajaj Allianz General Insurance',
     'Bwise- Pan India Recruitment & Training', 'Johnson & Johnson', 'Galtech Infosolutions Ltd.', 'Cobblestone Energy',
     'JobDost', 'Crewscale', 'NoBroker.com', 'Bandhan Bank', 'Growmor Strategic Management Pvt. Ltd.', 'TALCHEMIST',
     'The Infinity Space', 'Prathigna.com HR Solutions Pvt.Ltd', 'Atom Technologies Ltd', 'TekPillar',
     'Industryjobs.in', 'INI Design Studio', 'JD Institute of Fashion Technology Official', 'Tech Mahindra',
     'Response Informatics', 'SumTotal Systems, LLC', 'TKC Design & Build Pvt.Ltd.', 'PaxOcean',
     'Master Builders Solutions', 'Novel Patent Services', 'Hetero Drugs Ltd', 'Searchline Database Pvt Ltd', 'Trell',
     'Siemens Gamesa', 'TautMore', 'Digiyou', 'Nyros Technologies', 'Golden Opportunities', 'Coding School',
     'Pidilite Industries Limited', 'Innova Solutions', 'Praxsol Engineering Private Limited', 'FARMORG FOODS',
     'Bloomingdale International School', 'Tulasi Seeds Pvt Ltd', 'HCL Technologies', 'GITAM Deemed University',
     'Akrivia HCM', 'OnePOS Retail Solutions', 'PamTen Inc', 'Young Minds Technology Solutions Pvt Ltd', 'FABIT CORP',
     'KL University', 'EFFTRONICS SYSTEMS PRIVATE LIMITED', 'Inventrax', 'Xinthe Technologies',
     'Little Carrots India Private Limited', 'Inola Technologies', 'eProSoft', 'Hrishikesh Technologies',
     'Openlogix Corporation', 'PR INSIGHT Pvt. Ltd.', 'SJ Interiors', 'Aertsen Living', 'WHITE WILLOW SOFTWARE PVT LTD',
     'International Flavors & Fragrances', 'Lakshya International School', 'BIZGURUKUL', 'Basilmind', 'EducoHire',
     'ATLANTIS - The World School', 'Accord School',
     'Chirala Engineering College, Ramapuram, Beach Road, Chirala, PIN-523157 (CC-E9)', 'Uber', 'Ascent Health',
     'Amara Raja Batteries Limited', 'Click Travel - Corporate Travel Management',
     '360 Degree Engineering & Consulting Services Limited', 'SarvHR', 'CIEL HR', 'Agiliti', 'ConsultBae',
     'FOREFRONT Charity', 'Manipal Health Enterprises Pvt. Ltd', 'Transhill Management Services',
     'T.I.M.E. (Triumphant Institute of Managment Education)', 'KSRM college of Engineering',
     'Sri Venkateswara University', 'Parvathaneni Brahmayya Siddhartha College of Arts & Science',
     'Akrivia Automation Private Limited', 'Ioninks', 'ARK Media Wedding Stories', 'Mahendras',
     'RDP Workstations Pvt.Ltd', 'Agfa', 'Fasal - Grow More, Grow Better�',
     'Harman Connected Services Corp India Private Ltd', 'S.V.TURBO ENGINEERING WORKS PRIVATE LIMITED', 'Tessolve',
     'Siemens Gamesa Renewable Power Private Limited', 'Self Employed', 'Precision Infomatic (M) Private limited',
     'Apps Associates', 'Precistat IT Solutions Pvt Ltd', 'Vegazva Group', 'Kakaraparti Bhavanarayana College - India',
     'innData Analytics Private Limited', 'InterviewBuddy�', 'Corpware Technologies pvt ltd',
     'Savvy Software Solutions Inc', 'Microsoft Mechanics', 'Machint Solutions', 'GoInformative',
     'Softrance technologies pvt.ltd.', 'Sails Software Solutions', 'Appen', 'Exygo.in', 'Skandhanshi Infra Projects',
     'Inspiredge IT Solutions', 'Triovision Composite Technologies Pvt Ltd', 'Flipkart', 'Omni Auto Ltd - India',
     'LAYA Resource Center', 'Green Tech Industries India pvt Ltd', 'Samasra Soft Inc',
     'Tummala Infrastructure Limited', 'Project Resource Ltd', 'Mold-Tek Technologies Limited',
     'SRI LAKSHMI PRABHA ENGINEERING INDUSTRIES PRIVATE LIMITED', 'Embedded Technology Labs', 'Alstom',
     'Balaji Holograms Stickers Gujarat', 'Kajal Enterprises', 'Xiaomi India', 'Quick Heal', 'ByteOrigin',
     'Sentini Bioproducts (P) Ltd.', 'Brunel', 'Astro', 'Inventiz', 'OIL FIELD INSTRUMENTATION', '3Si Eco Power',
     'Otis Elevator Co.', 'Amaraja Batteries Limited Mahalaxmi Pla', 'Vasavi Power Services Pvt Ltd',
     'Ravileela granites limited', 'Avani Recruitment Consulting', 'Hubbell Incorporated', 'Achievers Spot',
     'KOBELCO Construction Equipment India', 'Texas Review', 'Blitz Jobs', 'Teejay Lanka PLC', 'Colgate-Palmolive',
     'Allana Group', 'JUST BREADS', 'Mintifi', 'KMV Spaces', 'Ansell', 'Prime Placement', 'HDFC Bank',
     'Future Tech IT Global Services Pvt Ltd', 'The Verticals', 'JAMES WALKER INMARCO INDUSTRIES PRIVATE LIMITED',
     'SRI HARANATHA OIL TRADERS', 'Vivify Healthcare Pvt. Ltd.', 'RESOLVE ITECH CORP', 'Taproot Foundation',
     'SureClaim', 'Anblicks', 'KAPARDHI DOCTORS RECRUITMENT AND PLACEMENT SERVICES Pvt.Ltd.,',
     'Hearing Solutions India', 'Talent Zone Consultant', 'Arise Software Solutions',
     'Vishnu Dental College, Bheemavaram', 'Talent Zone Consultants', 'Datapro Computers India Private Limited',
     'OMNI Hospitals', 'Ample Leap', 'ReLiva Physiotherapy & Rehab', 'Omnia Ventures', 'Spa Staff.com',
     'School Of Leadership', 'AGS Health', 'Newton House', 'NRI ACADEMY OF MEDICAL SCIENCES, GUNTUR',
     'Absolute Minds Medical & IIT Academy', 'NTR University of Health Sciences',
     'Herbalife International India Pvt. Ltd.', 'Herbalife Independent Distributor', 'Diebold Nixdorf',
     'BOTHRA SHIPPING SERVICES PRIVATE LIMITED', 'HR CHAMBERS OUTSOURCING PRIVATE LIMITED',
     'Astin Overseas Consultants', 'Imerys', 'Multifit Wellness', 'Navata Road Transport', 'Eruvaka Technologies',
     'Arthan', 'Techelita Pvt.Ltd.', 'Technoxis', 'JDC Recruitment Services', 'Maverick Overseas Consultancy',
     'Duruper', 'Vugido', 'Absolin', 'Infotenix', 'Bhuvi IT Solutions', 'Socially X Influencer Centric Pvt. Ltd.',
     'Invensis', 'Candour Technologies', 'Krify', 'RESOURCE ACCESS MANAGEMENT SOLUTIONS PRIVATE LIMITED',
     'Swaniti Initiative', 'ABHIBUS SERVICES (INDIA) PRIVATE LIMITED', 'Innogeecks Technologies Private Limited',
     'CubeDigiCo Incorporated', 'Aerosimple', 'Integrated Personnel Services Limited', 'Waltair Business School',
     'Invincible Software Solutions Integrated Pvt. Ltd', 'iNVESTT.in', 'Galaxy Tech Solutions', 'SkyGoal Inc.',
     'Honeyy Group', 'Hetero', 'ACE Engineering Academy', 'UltraTech Cement', 'Conduent', "L'Or�al", 'Dropshop Network',
     'Aakash Educational Services Limited', 'Qaurus Limited',
     'Peter England Fashion & Retail Limited (Aditya Birla Group) C/O Manp', 'PepsiCo', 'udaan.com',
     'Amazon FBA Sellers', 'NIIT Limited', 'The Jurni', 'MerWin Growth Partners', 'NASSCOM', 'Pick a Book India',
     'FOUR SQUARE HOMES PRIVATE LIMITED', 'IFORTIS WORLDWIDE�', 'Knitsol UK', 'DS Marketing',
     'SELCO SOLAR LIGHT PRIVATE LIMITED', 'Online Internship-Techvolt Software Pvt Ltd',
     'Haidri Beverages Pvt. Ltd. PepsiCola International Franchise', 'iFuture Globistic Limited', 'RGBSI',
     'Hiring Alert', 'Job & Career Opportunities', 'Career For Freshers', 'Oil & Gas and Marine Jobs',
     'ConstructionPlacements Official', 'Machine Learning India', 'Chemical Jobs Postings',
     'Global Freelance Recruiter', 'Hshelpinghand - The Hemant Sharma initiative', 'Vansh Consulting', 'FMCG JOB',
     'Opportunity Track', 'Fresher Jobs Update', 'PloPdo', ' Government Jobs Alert', 'PM School', 'LearnToDrill',
     'Freshers job', 'Jobs in India', 'Mutual Funds Sahi Hai', 'Webmasters4SEO', 'Pharma Job Vacancy', 'Sohum Inc',
     "TecMint: Linux Howto's Guide", 'Agile For Growth', 'The Invisible Paintbrush', 'TEXTILE APPAREL JOBS', 'PuneJob',
     'Zresta', 'Vertical Talent Solutions', 'Symbiosis Centre For Management and Human Resource Development',
     'Maan Source', 'Campus Jobs', 'India Development Review (IDR)', 'ArtZolo.com', 'Folkulture',
     'Vacancy Finder India', 'Aheshan Traders', 'Softcell Technologies Pvt. Ltd.',
     'Indian Hospitality Networking Website- Hozpitality ', 'Drone Federation of India',
     'Good Jobs (Jobs For Social Good)', 'NoConsultant.Com - Jobs Without Consultancy', 'TalentServe',
     'Pharma Info | Jobs', 'All Courses 100% Free - DealsOnChat', '100X.VC', 'FreshersWall.com', 'All Things Apple',
     'Latest Job Updates for Job Seekers', 'ClinoSol Research', 'Jai Narain Vyas University', 'The SMART Taxi',
     'IT Jobs', 'Jobformore', 'The Electrical Engineers Factory ( TEEF )', 'XtraLeap', 'SPF Shrimp Feeds',
     'CloudEnd Platform Inc', 'Guru Nanak Khalsa College of Arts Science & Commerce', 'Free Fire', 'VAIDHA LAW JOURNAL',
     'Smart Mind', 'KIDZEE PRESCHOOL - India', 'N Space Tech', 'Sustainable Systems International',
     'Bezwada Biomedical, LLC', 'Manthan - The HR Club of IIM Visakhapatnam',
     'Fresher Wipro, IBM , TCS, Accenture, and HCL Based Online Job Internship With Certification Course',
     'Shopify Developers Experts', 'Cannasis Wellness', 'Suraksha', 'LogicStats', 'Typito',
     'Transcad Engineering & Detailing, LLC', 'MVGR College of Engineering', 'vARKY Technology Solutions',
     'BIM Era Private Limited', 'Finance and Economics Club, IIM Visakhapatnam', 'Koal Technologies Pvt Ltd',
     'Quant Solar', 'Agshots', 'PUBG Mobile ', 'Janyaa', 'La Political Action Committee', 'Instrumentation Tools',
     'Indian Biomedical Skill Consortium', 'Kshvid News', 'Global Center For Online Learning', 'Lets Gtok',
     'HaleMind Inc.', 'NVK Staffing Solutions', 'PMI Pearl City, Hyderabad Chapter', 'InterviewBuddy Pro',
     'Shivajirao S Jondhale College of Engineering', '3R ZeroWaste Private Limited', 'Interior Designer',
     'GOODYEAR SOUTH ASIA TYRES PrivateLimited.', 'Merademy ', 'Better Careers', 'GetHired ',
     '#ElectricVehicle (#EV) Zone - EV Zone.in', 'Student Global Cause Foundation', 'Global Careerfeed',
     'Teaddle Media', 'Nerd For Tech', 'cajobportal.com', 'Dee Vee Shipmanagement',
     ' SAP MM/FI-CO/SD/PP/QM/PM/HR/ABAP/BASIS Online Training', 'Freelance Writing Services', 'Finatics', 'KATCHERI.IN',
     'Talent Management Consultancy', 'Citizens for Public Leadership', 'Quantum_AI Quantum Computing',
     'Actuators Educational Institute', 'ProxyPrep', 'StepUp Analytics',
     'Check My Universe� LLC Technology with Purpose and Impact', 'OIP Energy Services', 'VDMA India',
     'B3 - BRAIN BEHIND BRAND', 'India Confidential Company', ' Lo Job Uthalo', 'Job Dhundo', 'Hack This Fall',
     'Steel & Metallurgy', 'Polynotech', 'The Sikhs Triumph', 'GForce Consulting Solutions (OPC) Pvt. Ltd.',
     'Mad About Sports', 'Mentro', 'IIM Calcutta Innovation Park', 'Vogue Italia',
     'CodeSpeedy Technology Private Limited', 'Y-East', 'Accumen Wealth Pvt Ltd', 'MLSA - Tesseract Coding',
     'The Placement Diary', 'HUNGERY BITE', 'Drone Helpline', 'Channels Inc.', 'EXTRA! Insights', 'The Sealuminati',
     'Brood Handicrafts', 'Overseas Placement Service, India', 'SavaHire', 'JOVS', 'XXX', 'Mahila Money', 'Planboo',
     'Startup Instant Pvt. Ltd.', 'Hyperweb AI', 'GreyStory Content', 'Silicon Subcontinent', 'FinFlee', 'PsyTech',
     'Delphic', 'India Foundation for Education Transformation', 'Twippin', 'Argonaut', 'CodeDeeper',
     'Zigma Learning Co.', 'School of Life', 'Zantrik Technologies Pvt. Ltd.', 'Curry In The Bank', 'BufferMint',
     'TecValue', 'Silver Lining With Shreya', 'Haiku Design House', 'ClickOnix Digital Media', 'Easypie App',
     'Mad Over CS', 'Baweja Media', 'YES Tibetan Career Centre', 'Konpod', 'Norm School', 'getvouch', 'itmadeeazy',
     'Reading Pills', 'ArunachalUpdates', 'AshwinTalks', 'GeoDigital Solutions', 'Remotely Jobs',
     'Alpha Omega Knowledge Hub', 'DSC NIT Arunachal Pradesh', 'Arunachal Pradesh Public Service Commission',
     'Skill O FLy India Private Limited', 'AgriVision4U', 'Digital Notice', 'Adish Digital', 'Forethought India',
     'neuralclass', 'QuickGhy', 'She For Change', 'AgSpeak�', 'Leadsark 2.0 Organic Lead Gen', 'Feynn Labs', 'Bnwwear',
     'HM Ventures ', 'Profound Alley', 'HM Journal', 'Northeast Jobs', 'PetroleumBuddy', 'OPEYN', 'Adv Santosh Sharma ',
     'Eco Alarmist', 'Work Studio Coworking', 'SuccessPick', 'Basic Humanity', 'BrandHeft', 'Government Jobs Updates',
     'Cygnus Marketing', 'Law Pulse', 'Camping Co.', 'Exhibit G', 'NE Rising', 'Arras India ', 'The Gloo',
     'Baatein Ankaheesi', 'Brightcrop Agro Products Private Limited', 'Civil Gyan', 'Spickas', 'Inventing Idea',
     'Futurists', 'Covenant Consultants Guwahati', 'Developer Student Club (AEC)', 'PCF Agri-Tech', 'AssamCareer.com',
     'Success Drive', 'Tezpur University Alumni Association', 'Career Assam', 'Jobs Force India',
     'Blindspot Media-Digital Marketing Agency', 'Binbag', 'consPeer', 'Silicon & Company', 'Gamification Labs',
     'Training and Placement Cell, BIT Patna', 'Trisna Films�', "St. Xavier's High School - India",
     'Sahicollege Mentoring', 'PowerWatt Technologies', 'Red Dot Foundation-Safecity',
     'CLINIASSURE - A Clinical Research Training and Mentorship Firm', 'Sneh', 'Advanced Excel Courses ',
     'Patna High Court Lawyer', 'Dr. Zakir Husain Institute & IIBM',
     'Microsoft Excel Training Tutorial: Learn in 24 Hourse', 'Quayo Retails Private Limited',
     'Kaleidoscope Child Foundation', 'Bada Business Pvt. Ltd. (IBC)', 'Bihar Yoga Bharati', 'Karekeba Ventures',
     'Digital Deepak', 'Agile HR Consortium', 'Tuition India', 'Lotus Media', 'EasyWebes',
     '6rahiya Enterprises (OPC) Private Limited', 'Bharat Entrepreneurs Network', 'Comm4ease ', 'Timidlly', 'Canstruct',
     'Home Decor', 'Hanuman', 'Oplus Cowork - Coworking, Community, Connect', 'WebSolGuru', 'Loving Parents',
     'Singh ceramics', 'Stock Consultant Bihar', 'Legal Aid Law Firm', 'SUVIDHAJOBS.COM', 'Linkedin Local Bihar',
     'Rauda Solar Energy (OPC) Private Limited', 'DIGIAFF', 'Media-Box', 'AccionLAND', 'TECHBOAT STUDIOS',
     'Aryavart Institute of Technology', 'Confidential', 'Job4freshers', 'Mad Over Marketing (M.O.M)', 'Angular Jobs',
     'Career Encyclopedia', 'Ace Your Career', 'parikshram.com | Software Testing Studio', 'Ease My Job Search',
     'JavaScript', 'Jovian', 'Quolum', 'Marine Insight', 'OffCampusJobs4u.com', 'TotalCloud (Acquired by Qualys Inc)',
     'Hashnode', 'CA Hiring : Campus and Offcampus ', 'Coacharya', 'Headstrt', 'Allrounder Cup', 'The Job Hunt',
     'CMTI - Civil Engg Connect', 'The Product Tree', 'THC Consulting & Advisory Services', 'The Product Folks',
     'IKYA Human Capital Solutions - A Quess Company', 'Phyllo', 'Buildkonnect', 'First Job',
     'The/Nudge Centre for Social Innovation', 'IMPACT2030', 'Upaya Social Ventures', 'Tezsure', 'Community Classroom',
     'The Intern Academy', 'Jobdae ', 'Careers in Impact', 'Radian Engineering Solutions', 'Mr. Capital� - Highlight',
     'RethinkingUX', 'Unschool Learning', 'ReadOn', 'Fireside Ventures', 'Bk2Wrk', 'Tenzai Systems', 'GrowthX',
     'Agilemania ', 'Avianco', 'Gulf Career', 'GULF JOB', 'JOBS AT GULF', 'Biomedical Job Portal',
     'The Test Tribe Community', 'GULFWalkin Jobs for Indians', 'Medical Coding Jobs',
     'ExtraSlice - Office Space Simplified', 'Coinwaygroups ', 'HabitStrong', 'totHR', 'TechnoparkToday', 'Udemy',
     'Humans of Kerala', 'COCHIN SHIPYARD LIMITED', 'Fine Dining Indian Ltd',
     'eHackify Cybersecurity Research & Trainings', 'StackRaft', 'Internet Leads Training', 'ASIMOV Robotics',
     'benefigo', 'CEO', 'Technopark Jobs', 'Ecesis Engineering Services', 'Cami.AI', 'Advocate- Independent Practise',
     'AlgoUniversity (YC S21)', 'Excalibur Health and Safety', 'Vinod K Agrawal & Associates, CA',
     'TechPhant Consulting Group', 'The Crefft', 'Chalbo India Private Limited', 'Telloway',
     'Bhartiya Janta Party (BJP)', 'Neeti Shastra', 'MyWays', 'Government Jobs for Freshers', 'VOICE OF HEALTHCARE',
     'Public Policy India', 'VCBay', ' Atmnirbhar Hum', 'Metro Rail Today', 'Spaceonova�', 'Tech Burner',
     'Internship & Training', 'Hunt for Success', 'HRDC Professional', 'Metallurgical Engineering', 'Leaderspace',
     'Naukri finder', 'InnoRenoVate ', 'The Test Chat Community ', 'HireKul', 'Aaryan Creations',
     'IDEX Accelerator- Global Fellows Program (IDEX Fellowship)', 'Parmar Consultancy Services',
     'Indian School of Development Management (ISDM)', 'Kapdec', 'Tatkshan AQL Pvt. Ltd.', 'Agency Reporter',
     'Data Glacier', 'Atal Incubation Centre- BIMTECH', 'Game changers 23', 'TiE Delhi-NCR', 'Civilverse',
     'VLSI Expert Private Limited', 'Sensegrass Inc', 'The Transformational Lab', 'TheJobSeekers',
     'Stap Management Consultants', 'Predictions For Success', 'International Advanced Computing Conference (IACC)',
     'SFDCPanther', 'Minimal Tweaks', 'Aspire: CA & CFA', 'Abyom SpaceTech and Defence Pvt. Ltd.', 'Cirkled in',
     'The Management Jobs', 'Indian Petroleum Association', '4Ps News', 'Hirepedia', 'ASTROLOGY',
     'Sai Placement Solutions', 'EDGE EXECUTIVE ', 'Betterdrones', 'The Bath Boutique', 'National CoE',
     'Headsmart Solutions', 'BSG Hospitality', 'OWASP Seasides', 'Mechatronics Automation', 'Xenerx', 'FanClash',
     'Novacare Packaging Pvt Ltd', 'Travelholicq', 'Dautya Aerospace', 'AirCampus',
     'FiiRE - Forum for Innovation Incubation Research and Entrepreneurship ',
     'Integrated Biopharma AND Pharma Solution', 'algokart.in ', 'AJF Innovations', 'UNAKTI',
     'GDG Goa (Google Developer Groups)', 'Jobs For Goan (Jobs in Goa)', 'Atal Incubation Centre, GIM',
     'E-nova Technologies', 'PROSPERiTREE - Pune and Goa', 'Goa Prism', 'Lemiride', 'HONEST STRUCTURES',
     'Goa Electronics Limited', 'Caarya', 'AppSec Media', 'Tandem Research India', 'Party Hunt', 'GOJOS',
     'Radical Technologies', 'Green Arrow Career Services', 'Kavaalya', 'Poker Sports League', 'CopperCodes',
     'Huloq Chatbots and Analytics', 'Yomorebi Hospitality Consulting', 'Well Then So | Design Studio',
     'Design and Code', 'StandWeSpeak', 'Rescape Technologies Private Limited', 'Legal Minds LLP ',
     'Stilldistilling Spirits ', 'Finvant Research Capital LLP', 'KiteTalks - Sport � Insight � Inspiration',
     'Planet Goa Magazine', 'Mrinq Technologies', 'Letcetra Agritech', 'Mechanical Jobs and Career',
     'Pharma Job ( Pharma Growth Portal )', 'Hindustani Jobs', 'Industrial Knowledge (nikunjbhoraniya.com)',
     'Java Developer Zone', 'Bharathidasan University', 'Chemical Engineering Blog', 'Petroleum Gate concepts',
     'TalentHire HR Solutions ', 'FORCE Biomedical', 'Free Udemy Premium Courses With Coupon',
     'DevangSolanki.Com - IT Enabler', 'Yoga with Urmi Pandya', 'Aileensoul for Job Seekers', 'Prominent Consultant',
     'WideInfoWeb LLC', 'MUKRAJ-INSIGHTS | Market Research Consultancy', 'SAP Openings', 'Sourcing & Supply Chain',
     'PHARMA-STATS', 'The LAW Learners', 'Appegic', 'SDP HR SOLUTION', 'Free PPT Templates Download',
     'InterCollege Network', 'Place1india HR Solutions - Job Placement Consultants Ahmedabad, Gujarat',
     'MIGFT: Recruitment (Data Collection)- Full Time Job| Work From Home| Part-time Job| Freelancing',
     'Hello Hoteliers Career Management PVT. LTD.', 'BEST OF HR Forum', 'Composites Excellence Centre of Asia ',
     'Training and Placement Cell, IIIT Surat', 'Bharat Inclusion Initiative', 'TURNAHEAD HR CONSULTANTS Pvt Ltd',
     'CS Jobs & Internship', 'Meru Accounting', 'The Shop Surat', 'Aspire Techno Consultants',
     'Synergy Resource Solutions', 'HR ASSOCIATION OF INDIA ', 'Food for Marketeers', 'MBA CHAI WALA ACADEMY',
     'The Younger Me Project (TYMP)', 'Suraj Steelmet Pvt Ltd', 'Whiteice Network', 'Perfect Sprout',
     'Sourcehub - The Recruiters', 'Bharat Udaan Mission', 'iCreate', 'The Job Man', 'Pick Your Job!!',
     'Career Blaze HR Solutions', 'Titan Capital', 'CREATORSHALA(Complay Digital Media Pvt. Ltd.', 'EJCL Services ',
     'Atom EI', 'Dev Placement', 'Campus Placement', 'Trifecta Capital', 'PharmaLinkin (Pharma Jobs ,Pharma Career)',
     'themunkees', 'EVreporter.com', 'Huddle', 'DMAasia', 'Digeesell', 'Hustle Post', 'LinkedInLocalI',
     'T & A Solutions', 'Our Brain Our Life --- Counselling, Psychology & Wellness center ', 'The StartupLab ',
     'WareIQ', 'HR GENIE', 'Wire2Hire', 'Wellcure', 'LENS Corporation', 'OutPlacement Heros', 'Rising Ahead',
     'Zamit India', 'Akadia', 'LikeMinds', 'Indian Small Business & Franchise Association - MSME.in', 'Zaakpay',
     'Reputation Today', 'CXOE Partners LLP', 'G R INFRAPROJECTS LTD.', 'Elliott Moss Consulting',
     'QwikSkills (Backed by 100X.vc)', 'Actuary Sense', 'CurioEd', 'Fincore Analytics', 'INACE.ORG', 'Techplayon ',
     'VN Consultancy Services', 'Ritewind LLP.', 'IMT Alumni Association', 'YourNest Venture Capital',
     'The IELTS TOEFL Centre', 'NavGurukul', 'BACK&PACK', 'Sajhe Sapne', 'Startup Success Stories',
     'HimScout Recruiters', 'Skin Elements', 'IIT Mandi Catalyst', 'parspec', 'Hethrive', 'Elate Digital', 'AltCampus',
     'Hill Ventures', 'Adhyay studios', 'FinServe - IIM Sirmaur', 'Vguard Industry Limited', 'E&I-Cell, IIM SIRMAUR',
     'HFIL Technologies Pvt Ltd', 'Infused Blends', 'Its Hemp', 'DCodein', 'Heaven In Himachal', 'Official Panda',
     'Fujiyama Power System', 'Law Audience', 'E-Cell, IIT Mandi', 'Slog Templates',
     'Civilified Infra Consultants Private Limited', 'Azad National Library & Study Center', 'Pro Athlete Nation',
     'AgroGuardian', 'PulsePlay Digital Private Limited', 'The Mountain Walker', 'Fascorp.in',
     'Go Into Digital Marketing', 'Alumni Cell, IIM Sirmaur', 'The Himalayan Chocolates', 'ONLINE SAILOR', 'MakeLives',
     'Himalayan Bhraman', 'HANOOR Herbal Cosmetics', 'VIVA Dental Clinic', 'Homestae', 'Himalayan Advocacy Center',
     'Zero To Infinite', 'Muditam Ayurveda', 'Vertosphere', 'Craffic', 'iTechHacks', 'Koshur Store',
     'FinThink | CA Career Assistance ', 'iKoshur', 'Kashmir Education Initiative', 'Jehlum', "Hack The Mountain's",
     'Localytee', 'Mountain Homestays', 'SID07 Designs', 'Ignou Student Zone', 'Educatio Learning', 'Finthink',
     'Malaz Foundation', 'Jobs in Srinagar', 'Genetico Research & Diagnostics Pvt. Ltd.', 'AdVorld', 'Namhya Foods',
     'Career jack academy', 'Aatish Management Consultants (OPC) Pvt Ltd', 'Mehta Law Associates', 'Talentstalking',
     'Techboxx', 'Digital Kong', 'Gatoes', 'Daskdan Innovations', 'Yarikul Infotech', 'Nimpact Technologies',
     'Industry Interaction Cell, IIM Jammu', 'gigfolio', 'Tyrads ', 'Groxery', 'KEI - A2STEM',
     'peppigo� A Fast Food Company', 'Qutbee', 'Gyawun.com', 'FlyKashmir', 'EcoKash', 'Jobs in Jammu',
     'OpScape - IIM Jammu', 'Beingkashmiri', 'Hitch Technologies', 'NIT Srinagar', 'TheVidhyalaya',
     'Cement Plant Optimization @ Cementindusneed', 'The Abram', 'Spinworx Corporation',
     'Entrepreneurship Development Cell, IIM Jammu', 'Internships & Trainings', 'Petroleum From Scratch', 'Augmintech',
     'Management Masters', 'CyberPeace Corps ', 'The Competition & Commercial Law Review (TCCLR)',
     'Hindustan Copper Limited', 'The Global Opportunity Youth Network', 'Startup Wonders',
     'Placement Services Pvt. Ltd.', 'Fametick Media', 'Floxus', 'Askmemetallurgy', 'Krishna World Wide Team',
     'Job Silo', 'Career Hotspot & Services', 'ileadHR', 'MidhaFin (MF)', 'MIHY Placement Service', 'Nonic Toothbrush ',
     'Khethworks', 'Path Advice', 'OFYCN', 'ANNADA COLLEGE, HAZARIBAG', 'Citrine Solution', 'Free The Hook',
     'Epanipuricart', 'Bluribo', 'College Finder', 'MI STORE', 'Business Academy',
     'Centre for Study and Research in Intellectual Property Rights, NUSRL Ranchi (CSRIPR)',
     'Educational initiative to create leaders for MORAL EVOLUTION for the safety of our future generation',
     'Supply Chain Management Inc.,', 'The Job Studios', 'AgrMayank Studios', 'IIM Ranchi UNGC-PRME ',
     'Optimize For SEO - Digital Marketing Agency', 'MadeByMaa', 'Monthlies', 'Tata Steel Industrial Consulting',
     'Konkuwan Herbs', 'Webgraph Worldwide', 'mLeAP', 'Digi Elephant', 'SMEATONS PROJECT PRIVATE LIMITED',
     'Pharma Job Portal', 'Employment News Job Updates', 'MX Recruitment - Australia & New Zealand', 'Linux Academy',
     'Aviation Jobs @ AeroNefs', 'Satvic Foods', 'TBH circle ', 'The Great Indian Lawyer ',
     'RC Project Consultancy (RCPC)', 'Law Express', 'Kisaan Helpline', 'DataFlair',
     'YCM Conflict Management & Mediation Initiative', 'Pharmaglobiz', 'Webtopp Digital Solutions',
     'CONTRACTSANDFREELANCE', 'A2Z Packaging Bazar Pvt Ltd', 'Deleted', 'Dream MBA Job', 'Paathshaala', 'Scholarsight',
     'Digital-talenthire', ' Teal Box', 'Helping Indians', 'Career Height', 'JobWob', 'Altered Security', 'MayaEats',
     'KI Technologies', 'NDAX', 'Detail Design Group', 'Government Jobs',
     'Qcfinance Python Data Science Blockchain Affordable Bootcamp Classes NYC Classes Courses Evening ',
     'SBJ Jobs & Training', 'Ez 4 Business Solutions', 'InternFreak', 'CBCT Magazine', 'Indian Jobs and Career',
     'Webiators Technologies PVT. LTD.', 'AASLink Media Network', 'Avantika Designeering Series', 'F and B Recipes',
     'CompEye VFX', 'Law Colloquy',
     'Medi-Caps Institute of Science & Technology , AB Road, Pigdamber (Rau) Indore-453331',
     'Maharishi Mahesh Yogi Vedic Vishwavidyalaya', 'Manipur University, Imphal', 'ARTSofINDIA.in',
     'Recognize Rise And Empower Association', 'STEP North East', 'Urban & Landscape Design Studio', 'PiCaSoid',
     'AstroSpaceTech', 'Library for All (India)', 'JP NE BUSINESS SOLUTION', 'TRINITY FOOD SAFETY SERVICES ',
     'Nibiaa Consultancy Pvt. Limited', 'Addble', 'Kege Loisang', 'AMA-RIA FASHIONS', 'Mitrang Technologies',
     'GM PHARMA', 'Shuttle24', 'Shutfab Clothing', 'TricksGalaxy', 'Medilane Foundation', 'Guardians Defence Academy',
     'Chingangbam Engineering & Consultants Pvt. Ltd.', 'Indigena Herbals', 'Tsquare Digital', 'LAMKA Transcribers',
     'CodeXP', 'eManipur', 'Manipur Sports House FC', 'Siroi Financial Consultancy Pvt. Ltd.', 'Midas Touch, Manipur',
     'NESisters', 'Greenland Technology Solutions', 'Tweak Learning�', 'Tripura Business', 'STRANGERS HOPE',
     'Business Manipur', 'Nautilus Creed', 'basicP', 'unibrowstudio', 'Tantha Entertainment ', 'Todays Mobile',
     'Lamjing IT Solutions Pvt. Ltd.', 'DHANESHWORI TRADERS', 'Mangall Infotechs Endeavor', 'Varity Store',
     'TRUEBLUE TOURS AND TAXI PVT.LTD', '10.Pink', 'KiliBeauty.com', 'The WARI Initiative', 'chiloindia',
     'North Eastern Indira Gandhi Regional Institute of Health & Medical Science (NEIGRIHMS)', 'Ed Lodge Initiative',
     'Meghalaya Energy Corporation Ltd', 'Zeitgeist, IIM Shillong', 'usHR Club - IIM Shillong', '24point0 Slide Store',
     'Ribovi', 'Barking Deer Entertainment', 'IT Committee - IIM Shillong', 'Bharat Impact - CSR in India', 'Muezart',
     'SSNetCom Pvt Ltd', 'Tea Country', 'Zeitgeist', "Creator's Hub", 'Kashayam Blends', 'Eastern Career Institute',
     'Poynt Sports', 'MomsCove', 'InTown Solutions', 'Inventiv Insights', 'Marketing Wire', 'Turbit Shillong',
     'Saindur Enviro ', 'Ruralnomics Pvt Ltd', 'NE Techno (P) Ltd', 'Purple Architecture',
     'Ignyte Talent Consultancy LLP', 'bdjobs.com.co', 'Sustainable Architecture For Earth', 'Blendink', 'NiConnect',
     'Spring Valley Farm', 'Impulse Social Enterprises', 'Half and One', ' Digital Marketing Online course',
     'Ashraful Alom', 'NElookup', 'Alienleaf Studio LLP', 'Polaris Solutions Enterprise', 'Roots Travellers',
     'Veritas Communications', 'Jalewa.com', 'TechSoul (GrowEagles TechSoul PVT. LTD.)', 'MOX India',
     'Machina Logic Technologies LLP', 'Kyrshan Foundation', 'Electrical Society_ NIT MIZORAM',
     'ALUMNI_ASSOCIATION_NIT MIZORAM', 'Sure Taxis', 'Concept 4E', 'manishstore', 'Digifu Digital Marketing Agency',
     'Mizoram Newz', 'Sunflower Electronics', 'Shah Dry Fruits & Nuts',
     "St. Peter's Higher Secondary School Chhingchhip", 'Dorpui', 'Mehtab Export House', 'TechMJ',
     '1st Impression Music', 'Zofisfed Limited, Mizoram', 'Pachuau Consulting Pvt Ltd', 'MARYLAND HOMESTAY',
     'Bulls Eye Career', 'Blue Steel Editing', 'Market Winget', 'Forever X', 'Pineapple India',
     'NoBoundarees | International Multicultural Experience', 'Tiyara, Inc.', 'My Assam Job',
     'ARK One Stop Digital Solution', 'Highland Dawn Media ', 'Wander Nagaland', 'SaaSCosmos', 'Nagaland State Lottery',
     'JungleFlit', 'McCormick Engineering, LLC', 'Clevemesh', 'Trek And Ride Expeditions', 'WJ Decor',
     'M/s NJ Hitech enterprises Contractor & Order Supplier', 'Bujulo.', 'Blue Yellow Key', 'KAKI ', 'Sandal Wood',
     'Listed NL', 'NagalandExpress', 'RA Consultant', 'Keystone Education Society', 'Ferns & Sepals', 'DOTTalks',
     'Providence Institute of Design & Media', 'The Northeast Window Magazine', 'Dizynet',
     'Village Handicraft Exporters', 'Blogcastor Dot Com', 'Jeraif', 'HexedLand.com',
     'Safe Haven Counseling, LLC (Indianapolis)', 'Amar Roller Flour Mill', 'Lottery Sambad Result',
     'Sales Development World', 'Imagi.NATION', 'OurNagaland.co', 'AutoHut India', 'Nagalad Tool Room & Trainng Center',
     'Membrane Ready Made Doors and Flush Doors', 'The Handsome Hub', 'AT STELLAR ', 'cricnova',
     'Toputen Infotech Enterprise Private Limited', 'ZubZub', 'Banashree', 'Pharma Jobs Post ', 'Legodesk ',
     'SPS HR Solutions', 'Reena Agarwal ', 'SEO Content Writer', 'GradSchool Connect',
     'Sigmato - Operations Club at IIM Sambalpur', 'Venkat Raman Patnaik', 'Sunrise Pixel', 'Law Mentoring',
     'Rath - N - Rath', 'COAL INDIA LIMITED, (CENTRAL MINE PLANNING AND DESIGN INSTITUTE LIMITED)',
     'BULTAMINDS VENTURE PRIVATE LIMITED', 'Rupal India', "Bikash's Quantum", 'Ekayana Advisory',
     'Microsoft Learn Student Ambassadors KiiT', 'Yavda Analytics Private Limited', 'Hajir Hai',
     'Business News This Week', 'Pie Rooms', 'Dr. Ajit Kar', 'Act with Ruturaz', 'The Physics Indica', 'Neukelp',
     'Bharti Consulting Inc', 'Gandhi & Co.', 'Beyonders', 'The Good Jobs', 'sevenkosmos', 'Travel with Ruturaz',
     'Intelliroot', 'FosterJEE', 'Subham-de-Labs�', 'HonourCreators', 'Codepth', 'Todayq', 'Online Earnings',
     'The SB Consultants', 'Typof', 'Go Green Consulting Pvt. Ltd', 'thelastplug',
     'BrightShell HR Solutions Private Limited', 'PRRO ', 'The IndianPreneur', 'Legoarch', 'SAP Jobs',
     'The Financial Doctors', 'Trendy Beat Network', 'Baba Farid University of Health Sciences',
     'Mittal Industrial Corporation', 'High Skills ', 'Compton Education', 'ZeroBucks ', 'Digital4design',
     'Toshan Creations', 'TeacherOn.com', 'Kiara Consultancy Services ', 'jiWeb Technologies',
     'AIC - Indian School of Business ', 'CnX Player - 4K HDR Media Player', 'Hmel Mittal Energy Limited',
     'WordPress Website Service', 'Amptize', 'Narang Staffing Solutions', 'Explorin', 'CHROSS', 'VS Placement ',
     'Inches N Feet', 'RGNUL Placement Cell', 'Monte Carlo Fashions Ltd', 'AtoPlay India.', 'Scurite', 'JP Web Agency',
     'Miles Ahead Consultants', 'Troll Kingdoms Media', 'Oxeliz Games Pvt Ltd', 'My Pahadi Dukan',
     'Sonalika International Tractors Limited', 'Netmente', 'ArchRecruiters', 'Punjab Youth Leaders Program (PYLP)',
     'Business Development Executive', 'HRithvi -The HR Club of IIM Amritsar', 'E-FABRIC HOUSE PVT. LTD ', 'The Blogy',
     'IWEBCODE', 'HackAcademy', 'Bajaj Electrical Industries', 'MLAIT', 'Bhatia Consultancy Services',
     'Fortune4U JOB PORTAL', 'NOOB 4rMY', 'Mindfull Junkies (Technology Solutions)', 'GovtJobsAlert.In',
     'Meraki Consulting & Staffing', 'Real Placement Group', 'ValueOptim', 'Hotel Jobs in India', 'Educore',
     'ITI And Diploma Jobs', 'A.M. Overseas Manpower Consultants', 'HAUTE ARTE',
     'Startup Chaupal� - Incubator & Angel Network', 'jobolic.com', 'NanoInfomatrix LLP',
     'Life Insurance Corporation of India - LIC', 'Salesforce Hulk', 'REAR RENEWABLE ENERGY ASSOCIATION',
     'Business Manager - HR Magazine', 'Atal Incubation Centre @ Banasthali Vidyapith ', 'Not Yet',
     'THEME ENGINEERING SERVICES PRIVATE LIMITED', 'LTR Magazine', 'Let The Data Confess Pvt Ltd',
     'Resurgo Consultants Private Limited', 'Paid Network India', 'Lawcutor', 'ICFAI University',
     'Converse Placement Services India Pvt.Ltd', 'Crayons Prompt', 'LearnCodeOnline.in', 'MoriazStudios', 'INAYAT',
     'ProductHood', 'IIM Udaipur Placement Office', 'Career Solutions', 'EduVisa Services Pvt. Ltd.',
     'Saisons Global Consultancy', 'Grow Hopes', 'NRACET Official', 'Enrichmentors',
     'VijaySur - The Media Consultancy Group', 'Zerodha Traders', 'Easy Tax Services', 'TheSocialComment',
     'Bullzeye Consulting(Media,Digital,Tech hiring)', 'City One Initiative', 'Sun Pharmaceuticals',
     'AIC - SMU Technology Business Incubator', 'YantraMedia', 'Presko Organic', 'Recruitersgig Consultants',
     'Impact Weaver', 'EDvantageLearn', 'YUVA the NGO', 'Cloudbelly', "Untap'd", 'TravelGangtok',
     'The Reverse Mentor Lab', 'Voyage', 'The Chakras Farm', 'SUKHIM.IN - Buy Sell NE Products', 'Thirsty Camel Inc.',
     'OurGuest.in', 'Drive to Northeast', 'Heal Bridge Pvt Ltd', 'SH1ELD Tech Infosec Solutions', 'Kokkivo Clothing',
     'Staple East', 'Serene Sikkim', 'Monk and Mountains Holiday', 'Kaalrav', 'Bilingual Vitae �', 'Zippy inc',
     'PRADHANBROS PVT LTD', 'Digital Marketing & SEO Consultant in (Gangtok) Sikkim', 'The Improwisers',
     'Gladiolus Language Nectar LLP', 'HypeX Media', 'InstinctandAnalysis', 'Invention Technical Services',
     'Hotel Dikiling', 'Gangtok Hotel Magnolia ', 'De.mi Solutions', 'Travorgs Holiday Tours', 'ETRIPTO.IN ',
     'Bluesea Gaming', 'Advanced Technical Training Centre (ATTC)', 'Spectrum International', 'Sikkim', 'Reverbs',
     'Mount Expedition Travels', 'Studio KCL Architects', 'kuzu', 'AMAZINGADVENTURE Pvt. Ltd.',
     'Ranibaan Sikkim Tours and Travels', 'HashCoder', 'Ethical Hackers Academy',
     'Motivational Lines� - Inspiring People To Do Better', 'Cyber Security News', 'GBHackers On Cyber Security',
     'Mechanical Engineering World', 'Madurai Kamaraj University', 'Freshersapp', 'vfxexpress ',
     'Brahmastra Aerospace Systems', 'GotoGulf.com', 'Jobs CA CMA CS & Updates', 'Follow in Consultancy',
     'Soc Investigation ', 'Prozenics', 'CA Firm', 'Investment Bankers Forum', 'Just SEO Things',
     'Ganapathi Bappa Moriya', 'Meru Consultancy Services', 'S2S SOFT LLC', 'Pienza', 'CI Global Technologies',
     'ZeroT.ai', 'Jyroo Inc.', 'PMO Now', 'Udyogaseva', 'teslaindia', 'Students Circles', 'The Startup Centre',
     'UXD Jobs', 'Isha Leadership Academy', 'Pluscorp Consulting', 'Finite & Co', 'Peritum Partners',
     'Galexon Engineering Industries', 'IIT MADRAS ALUMNI ASSOCIATION', 'Sharp Gaze Tech Services Pvt Ltd', 'Finsire',
     'Simply FRENCH', 'Jeyikkalam Foundation', 'TODAC ', 'GAIUS Networks (Flipped.ai)', 'Adiuvo Diagnostics Pvt. Ltd.',
     'Dvara E-Dairy', 'HYPSTUMA�', 'SaaSBOOMi', 'Pharma Jobs (Pharma Wisdom Jobs)', 'Way2Fresher', 'Job Available Here',
     'SaudiGulf Projects', 'Learn.MachineLearning', 'Quintessential (Quin) Design', 'Acceleron Corp',
     'Hiringhub360 | Work From Home, Internship, Fresher & Experienced Job and Career updates',
     'eLearn - Free Online Courses | 100%OFF Coupons |Udemy | Coursera | ', 'Sadhguru JV',
     'InfoSec WriteUps Publication', 'JustEnough Spark', 'SAP BASIS JOBS', 'Dallas Venture Capital',
     'AIMS - Akhil International Management Solutions', 'UMO.DESIGN', 'RetrieveAI', 'Think Prile',
     'FinTax Bookkeeping LLC - Accounting | Outsourcing/Offshoring', 'SRI Capital', 'InterviewReady',
     'SheJobs-Women Focused workforce job portal', '3Lines Venture Capital', 'BHEL Hyderabad', 'KnitFinance',
     'Google Crowdsource ', 'Linux Weekend Learning', 'The Inside Sales Consulting', 'Android++',
     'National Skills Network - NSN', 'KDex Global', 'Material Science and Engineering Journal', 'Widhya',
     'Freelance PHP & Python & Node.js developers', 'Naresh i Technologies', 'Seekamentor', 'IdeateNstart',
     'VOICE 4 Girls', 'ProlenTek', 'Gradvine', 'Kisan Express', 'The Lean Programmer', 'Arthashastra Intelligence',
     'GirlScript Agartala', 'Tripura Gramin Bank', 'TalkEng - Practice English Speaking | Live 1-ON-1', 'Fueler.io',
     'IBC JAKI BHOWMIK || BADA BUSINESS', 'Data Recovery Zone', 'ARTICLE WRITER', 'Eye Supervision', 'Digisolvent LLP',
     'DREAMSCAPE DESIGN AND CONSTRUCTIONS', 'DARKneuron', 'ilustraca', 'Hostcode LAB ', 'Darkkreator', 'SILPAKARMAN',
     'Global Transport Chain', 'Spirituality', "Let's DM", 'National Building Construction Corporation Limited',
     'Prasanta Startup -"Global Small scale business ideas and tips"', 'Health Spicy', 'SGEARS Infotech', 'KR Tech',
     'Curious Aspirant', 'GROSALE', 'TOKMEX', 'Mitansh Hindustan Limited', 'Mitansh Industries Limited', 'ArWeb',
     'The Creatif Lab', 'Placement Cell IIIT Agartala', 'TUKs ', 'Help Infinite', 'Medicapp', 'Exileex Technologies',
     'Super Green Art', 'Innovate for Sustainability', 'Hembro Infotech',
     'State Institute of Public Administration and Rural Development (SIPARD)', 'Packsie', 'HapInd', 'Software World',
     'Auradix Private Limited', 'Therapica', 'Efsolit Technology', 'TeamTechsupport', 'Organic Krafts ', 'ThePlannerss',
     'Math Institute', 'Personal Growth & Professional Development by Gaurav Misra', 'BioTech Times',
     'Civil Engineering Jobs', 'A Story Club', 'Eximius Ventures', 'The Finance Club, IIM Kashipur', 'Farmako (YC S20)',
     'Airwind Placement Services ', 'Petroleum Defs', 'Hilfee ', 'Foodtech_network', 'SantKhabar.com',
     'The Mentors Guru', 'Technical Guftgu', 'Project FUEL', '100% tested clinical research | Pharmacuticals',
     'Entrepreneur Lounge of India', 'CollegeStartups.in', 'Shubham Jain', 'Digantara ', 'MentMedia', 'SalesTub',
     'Varroc Engineering Pivate Limited', 'National Institute of Hydrology', 'KGS Interns', 'NirmalGyan Enterprises',
     'Engineerism', 'Freed', 'VigyanShaala International', 'Samanta Foundation', 'Saksham Group', 'orekahome',
     'R&B Research Center', 'Earthinators', 'DivIn ebiz', 'OwlSurf Digital', 'Journal of Applied and Natural Science',
     'Himalayan Writing Retreat. ', 'Dev Ethical Sustainable Crafts and Textiles-descatuk', 'Army Brat Official',
     'Sunrise Job Consultancy', 'ChaiSeYaari', 'BWT Experiences', 'GreenJams', 'Mahogany Organics Pvt Ltd',
     'BFIT Group of Institutions', 'EventCo', 'Ayurveda Clinics', 'Go2andaman.com', 'Lolos Ventures',
     'Hebrews 11:3 Evangelistic Ministries, Inc', 'Nideja Properties ',
     'Andaman and Nicobar Islands Integrated Development Corporation Ltd (ANIIDCO)', 'Guruchandra Tours and Travels',
     'ASTRA TECHZ', 'ShellWala.com', 'Dekho Andaman', 'Fort Holidays Andamans', 'Byrut Business Solutions',
     'InteCreate Factory Pvt. Ltd.', 'ByteHead', 'ARCOME builders LLP', 'LOISIR Adventures', 'GreenLife CSR',
     'Jawaharlal Nehru Rajkeeya Mahavidyalaya (JNRM)', 'TukPuk Tours & Event Management', 'WATCHESMK',
     'TSG Emerald View Hotel', 'NAV Andaman Tours & Travels', 'myandaman.com', 'AdOps services (Freelancing)',
     'Andaman Travel Lover', 'Andaman Game Fishing', 'Cafe 4', 'ExoticAndamans', 'Andaman Orient Holidays',
     'TIMEBIZ HR', 'TripExpress ', 'EcoPreen Solutions', 'Techpillar', 'AN Commune', 'Thomas Associates', 'ZuperAp',
     'Ocean Pearl Beach Resort', 'Three Geeks', 'Dream Holidays Andaman', 'Andaman World Travels Pvt Ltd',
     'SITPakz Solution Pvt. Ltd.', 'Nexden', 'Andaman Island Adventure', 'Webtech Solutions Port Blair',
     'Andaman Diaries', 'Anko Marine', 'RSR TOURS AND TRAVEL', 'Guide To Dive', 'Yaha Life ', 'digital dreamers',
     'Quadtrends', 'Haarvard Management Consultants', 'SanKrish Digital', 'NEVAR Systems', 'VNET INDIA', 'Chitrapata',
     'Chetak Travels Pvt. Ltd.', 'GoodLiving.Eco', 'Amazon Associates',
     'AIC-PECF (Atal Incubation Centre - Pondicherry Engineering College Foundation)',
     'ABI-Tech Solution Private Limited India', 'CITY 5', 'HeyDesk', 'Young Entrepreneur School ', 'Mpower Consultancy',
     'DD CONSULTANTS', 'Mahe Institute of Dental Sciences & Hospital', 'Lucas TVS, Pondicherry',
     'Interjet India Private Limited', 'CARUNA.in', 'Truecubix',
     'Grafiks Design:: Professional Photo Editing, Book Design & EBook Formatting agency.',
     'NAYAGI ENTERPRISES PRIVATE LIMITED', 'Future Gurukuls', 'Chrisoft', 'EMMARDE Steel', 'Dzyte',
     'Integrative Design Solutions Private Limited', 'Scribz Sustainable Venture', 'Roads And Journeys', 'Air Safa',
     'First Sustainable Data Services Private Limited', 'Ekhlas Designs Marketing',
     'Skilled Migration Consultants Pvt Ltd', 'Herby - Innovation with Herbs', 'aatomz research', 'JP INFOTECH India',
     'DigitalTechz', 'RAP Technologies (P) Ltd', '10xfreshers',
     'Udemy Course on LDAP Directory Services - showcase page', 'Genome-2-Bio-Medicine Discovery Center (GBMD)',
     'VDesign Technologies', "Dr Kiran Bedi's Book Reading with Children", 'Sumukha Hitech Products Industry',
     'Vectorworks Studio', 'XuFancheng Culture Study Center ', 'Hysys Technologies', 'Government Jobs in India',
     'Labellerr, end to end AI SAAS platform', 'SockSoho', 'Four-S HR Partners', 'The Placement Guru',
     'Graphical Addicts', 'Chandigarh Angels Network', 'Chaincode Consulting LLP', 'ReferMe', 'NETWORKINTERVIEW',
     'Bruoo, Inc.', 'PeopleGrids (Follow us for Jobs updates)', 'RGB Web Tech', 'HypnoMyths', 'Marketing Masala',
     'Zavvy Solutions', 'aabbccddd', 'Aiotize', 'BTES: bebo Education Services', 'IP WITHEASE',
     'Prowisdom Growth Private Limited', 'TiE Chandigarh', 'The Circular Collective', 'Dope Digital', 'Contestone Apps',
     'KidsUp Global', 'BRANDPIT PRIVATE LIMITED', 'Talbros Legal LLP', 'The Morpheus / Morpheus Gang', 'chase2learn',
     'Hardikkhetrapal. com', 'IIFC - Indian Institute for Financial Certifications', 'MoroEsports', 'Qoncepted',
     'Programming Buddy', 'Bittmax', 'Deepsync Technologies', 'VAS Mobitech Pvt Ltd', 'VecRep', 'Apptroops LLC',
     'Quantum Solution India', 'TheWireMonster', 'Photon Tadpole Studios', 'Whispering Homes', 'Hypnotism', 'Enthu.AI',
     'CyberCT', 'TheTechnoCafe', 'TechHackSaver', 'NOW Archicon Consultant', 'Book Keedas', 'CryptoDrive', 'int tin',
     'music hunt', 'FORTULER', 'Sports & Management Research Institute (SMRI)', 'ConceptOwl', 'IDofThings',
     ' Cord.travel', 'TinkerHub', 'FareFirst', 'BELFORT OUTSOURCING ', 'Chordify Management Consultants LLC',
     'Magnifez Technologies Inc.', 'BioGrid HealthCare', 'SINE health', 'Acrocede', 'Ronicz Technovationz Pvt. Ltd.',
     'Avant Garde Innovations�', 'Women in Management - IIM Kozhikode', 'Technisanct',
     'PLACEMENT CELL-COCHIN UNIVERSITY OF SCIENCE AND TECHNOLOGY (CUSAT)', 'Prime Ideas Consultancy Services',
     "D'Talang Management Solutions", 'Moonhive', 'Marshlo', 'MSM - Manpower Solution Mantra',
     'ASAP Recruitment - Sales Hiring Specialist', 'Finology Ventures Pvt. Ltd.', 'ah! Ventures',
     'Careerz Inn Placement Consultancy Pvt. Ltd.', 'CodeNicely ', 'Alcowhiz', 'Datta Electrical Engineeting Works',
     'ResilienceSoft', 'Mgm College Of Engineering & Technology', 'Magure Inc', 'Career Brain Consultancy',
     'Sanjivani Wellness Centre', 'CareerPotli', 'Ujjwal Patni International', 'Workie', 'ANM CONSULTANTS',
     'SSIIDDHEY INSTRUMENTATION PVT LTD', 'Bhilai Steel Plant, SAIL', 'India CSR Network', 'Skill Inc.',
     'Ethereal Corporate Network Private Limited', 'OpInCo Community', 'BAJAJ Real Estate', 'The Rural Press', 'GOELD',
     'INTERNATIONAL REVIEW OF HUMAN RIGHTS LAW', 'Roll on Road', 'LearnArt', 'Vedanta Digital', 'Edualgo Academy ',
     'KV CLINICAL RESEARCH SERVICES (Site Management Organization)', 'Vakeel Khoj',
     'Konsole Indya Communications Pvt Ltd', 'Indira Gandhi Krishi Vishwavidyalaya', 'Property in Chhattisgarh',
     'Taaz ITSolutions', 'Innodeed Systems Private Limited', 'Indian Elites', 'Strategum Eduserve Private Limited',
     'Astha Innovations', 'CoalMint', 'LIFE EDUCARE Pvt. Ltd.', 'Xhitiz ITSolution', 'O.P. Jindal School',
     'Chartered Engineering', 'Durga Steel', 'Astey Technologies', 'BlueBanyan Technologies Pvt. Ltd. (India)',
     'Lalganga Builders Pvt. Ltd.', 'MEHTA STEELS', 'Central Business Solutions',
     'National Institute of Technology Raipur', 'Guru Ghasidas University', 'Indian Institute of Management Raipur',
     'Vinayak Job Consultant', 'Dr. C. V. Raman University, Kota Bilaspur', 'Nolte India', 'SteelMint',
     'Epitome Training & Recruitment Consultants', 'Nectar Infotel ', 'Sjain Ventures', 'GATE ACADEMY',
     'Techment Technology', 'RNM India', 'Jain Software', 'Technovate IIIT Naya Raipur',
     'Hidayatullah National Law University, Raipur', 'ERCGroup', 'Svamitva Group', 'Claro Energy ',
     'SKS Ispat & Power Ltd.', 'Merlin Group', 'Steel Infra Solutions Pvt. Ltd. (SISCOL)', 'Amicus Technology',
     'SteelMint Events', 'Internet Marketing School', 'Civil Guruji', 'ITM University, Raipur',
     'Institution of Safety Engineers (India)', 'St. Thomas College Bhilai Durg', 'Learning Spiral Pvt. Ltd.',
     'Steel360 ', 'ATAL BIHARI VAJPAYEE UNIVERSITY (ABVP) BILASPUR', 'Samarthan-Centre for Development Support;Bhopal',
     'MindLabz Media Tech Private Limited', 'Entrepreneurship Cell, NIT Raipur', 'Krishna Public School Raipur',
     'The Digi Jugad', 'CashPays', 'Test-Company', 'aispam', 'Google', 'Amazon', 'TED Conferences', 'LinkedIn',
     'Forbes', 'Unilever', 'LinkedIn Guide to Networking', 'Microsoft', 'Apple', 'Harvard Business Review', 'IBM',
     'Nestl�', 'Business Insider', 'The Wall Street Journal', 'Tesla', 'Deloitte', 'Netflix',
     'Tata Consultancy Services', 'Accenture', 'Meta', 'Oracle', 'Johnson & Johnson', 'LinkedIn News',
     'The New York Times', 'Procter & Gamble', 'The Coca-Cola Company', 'Amazon Web Services (AWS)', 'PepsiCo', 'EY',
     'NASA - National Aeronautics and Space Administration', 'Shell', 'Hays', 'Siemens', 'VAGAS.com', 'HP', 'Cisco',
     'Infosys', 'Wipro', 'LinkedIn Marketing Solutions', 'Nike', 'The Walt Disney Company', 'Adecco', 'Pfizer',
     'Cognizant', 'GE', 'Huawei', 'World Health Organization', 'McKinsey & Company', 'Bayer', 'United Nations',
     'Capgemini', 'PwC', 'Dell Technologies', 'Nubank', "L'Or�al", 'Bloomberg News', 'Walmart', 'Insider, Inc.',
     'World Economic Forum', 'Samsung Electronics', 'Citi', 'Crossover for Work', 'Chevron',
     'Hewlett Packard Enterprise', 'UNICEF', 'National Geographic', 'Ford Motor Company', 'CNN Business', 'Salesforce',
     'Adobe', 'Inc. Magazine', 'CNN', 'HCL Technologies', 'Ambev', 'J.P. Morgan', 'GSK', 'Bp', 'Schneider Electric',
     'Boston Consulting Group (BCG)', 'Sanofi', 'Goldman Sachs', 'Novartis', 'TechCrunch', 'SEBRAE',
     'JPMorgan Chase & Co.', 'CNBC', 'HSBC', 'Michael Page', 'General Motors', 'Intel Corporation', 'SAP',
     'LinkedIn Learning', 'EXAME', 'Banco Ita�', 'Tech Mahindra', 'Adidas', 'Petrobras', 'Vale', 'Abbott', 'Danone',
     'Boeing', 'Roche', 'ExxonMobil', 'Schlumberger', 'Simon Sinek Inc.', 'Starbucks', 'Spotify', 'SpaceX', 'TIME',
     'Entrepreneur Media', 'GitHub', 'Pequenas Empresas & Grandes Neg�cios', 'Natura', 'GE Power', 'Uber', 'Honeywell',
     'ManpowerGroup', 'Philips', 'Morgan Stanley', 'Mondel?z International', 'Bank of America', 'H&M', 'Fortune',
     'Merck', 'Vodafone', 'Marriott International', '3M', 'BRF', 'Halliburton', 'WIRED', 'Santander Brasil', 'Airbnb',
     'Colgate-Palmolive', 'United Nations Volunteers', 'Folha de S.Paulo', 'Ericsson', 'Interesting Engineering', 'DHL',
     'GE Healthcare', 'CHANEL', 'Louis Vuitton', 'BASF', 'Baker Hughes', 'The Atlantic', 'Lockheed Martin', 'Aramco',
     'Cargill', 'Wells Fargo', 'JBS', 'The World Bank', 'Centers for Disease Control and Prevention', 'Gerdau', 'UNDP',
     'TikTok', 'VMware', "McDonald's", 'Thomson Reuters', 'The Washington Post', 'Cheddar News', 'Bradesco',
     'The HEINEKEN Company', 'Deutsche Bank', 'American Express', 'Inter', 'Hilton', 'AT&T', 'Qatar Airways',
     'Warner Bros. Entertainment', 'Santander', 'Genpact', 'Robert Half', 'GOL Linhas A�reas', 'Looking for Job',
     'Bloomberg LP', 'Banco do Brasil', 'Target', 'UPS', 'Google Cloud', 'Stellantis', 'Fast Company', 'SEPHORA',
     'Magazine Luiza', 'DXC Technology', 'Gucci', 'JLL', 'Twitter', 'Caterpillar Inc.', 'YouTube', 'InfoMoney',
     'Boehringer Ingelheim', 'Adweek', 'Bain & Company', 'Nokia', 'LTI - Larsen & Toubro Infotech', 'AECOM',
     'Al-Futtaim', 'Medtronic', 'USAID', 'The Est�e Lauder Companies Inc.', 'Verizon', 'Jacobs',
     'Eli Lilly and Company', 'Kelly', 'Gartner', 'LinkedIn Not�cias', 'Volvo Group', 'Majid Al Futtaim',
     'Kellogg Company', 'Empregos.com.br', 'BAT', 'Visa', 'UOL', 'Dell EMC', 'Ogilvy', 'US Army', 'Cacau Show',
     'Diageo', 'Recode', 'FedEx', 'Novo Nordisk', 'Nissan Motor Corporation', 'IQVIA', 'The Kraft Heinz Company',
     'Grupo Botic�rio', 'UnitedHealth Group', 'Valor Econ�mico S/A', 'Eaton', 'Grupo Carrefour Brasil', 'Globo',
     'Modis', 'Hotel Jobs | JobKing.org', 'HBO', 'Sony Pictures Entertainment', 'Coursera', 'Stone', 'Upwork',
     'Credit Suisse', 'Weatherford', 'Continental', 'MIT Technology Review', 'Johnson Controls', 'Confidencial',
     'Four Seasons Hotels and Resorts', 'Grupo-estado', 'DHL Supply Chain', 'LinkedIn Noticias Am�rica Latina',
     'Ad Age', 'Renault Group', 'Atos', 'U.S. Department of Veterans Affairs', 'Civil Engineering Discoveries',
     'Unimed do Brasil', 'Korn Ferry', 'Computerworld', 'ConocoPhillips', 'Accor', 'Rolls-Royce',
     'CIEE - Centro de Integra��o Empresa-Escola', 'BlackRock', 'Red Hat', 'Mayo Clinic', 'Americanas s.a.',
     'Confidential', 'IFood', 'Bill & Melinda Gates Foundation', 'Mars', 'John Deere', 'CNET',
     'LinkedIn Talent Solutions', 'Bristol Myers Squibb', 'KPMG US', 'Lojas Riachuelo S/A', 'Votorantim Cimentos',
     'Kimberly-Clark', 'Reckitt', 'United States Department of Defense', 'Lojas Renner S.A.', 'HackerRank',
     'Mercado Libre', 'ADP', 'CBRE', 'Via', 'Mastercard', 'Henkel', 'Tencent', 'PayPal', 'Qualcomm',
     'Philip Morris International', 'Manpower', 'Robert Walters', 'Hyatt Hotels Corporation', 'QatarEnergy', 'Mashable',
     'Valeo', 'Takeda', 'Grupo Arcor', 'Mindtree', 'Modern Healthcare', 'HERMES', '�poca NEG�CIOS', 'Leroy Merlin',
     'NVIDIA', 'Nielsen', 'Sony', 'Thermo Fisher Scientific', 'Dow', 'DuPont', 'Instagram', 'Northrop Grumman', 'Xerox',
     'Aon', 'Electronic Arts (EA)', 'Amgen', 'FCA Fiat Chrysler Automobiles', 'Stryker', 'The LEGO Group', 'Syngenta',
     'C&A Brasil', 'Sodexo', 'FAO', 'Think with Google', 'Teva Pharmaceuticals', 'Delta Air Lines', 'BOMBARDIER',
     'Gi Group', 'Safra', 'Whirlpool Corporation', 'Wyser', 'Accounting Today', 'InfoJobs', 'Education Week', 'Ubisoft',
     'IHG Hotels & Resorts', 'OYO', 'AbbVie', 'LUANDRE CONSULTORIA', 'Cushman & Wakefield', 'ByteDance',
     'Walt Disney World', 'Anglo American', 'Siemens Energy', 'LG Electronics', 'Stack Overflow', 'Burberry',
     'Project Management Institute', 'Red Bull', 'Hospital Albert Einstein', 'WeWork', 'MSD', 'GPA', 'The New Yorker',
     'Udemy', 'Ralph Lauren', 'Mercado Livre Brasil', 'CEVA Logistics', 'PUMA Group', 'Cartier',
     'Sony Music Entertainment', 'Slack', 'Assa� Atacadista', 'Sicoob', 'Lazada', 'SAS', 'WUZZUF', 'Vagas Empregos',
     'Apex Systems', 'The Janssen Pharmaceutical Companies of Johnson & Johnson', 'Klabin', 'AMD', 'Ifanr', 'AIG',
     'NES Fircroft', 'Bunge Brasil', 'Hitachi', 'BBVA', 'American Airlines', 'CyberCoders', 'NBCUniversal', 'TEDx',
     'SHRM', 'Fluor Corporation', 'ZF Group', 'Lenovo', 'UN Women', 'Hotel Jobs Worldwide', 'Jaguar Land Rover',
     'NTT DATA Europe & LATAM', 'Self Employed', 'Everis', 'Sasol', 'CGI', 'Baxter International Inc.', 'SABIC',
     'Luxottica', 'Ra�zen', 'Kaiser Permanente', 'Siemens Healthineers', 'Porto Seguro', 'Sicredi', 'TransPerfect',
     'Bechtel Corporation', 'Central Nacional Unimed', '??? ??? ????', 'Vivo (Telef�nica Brasil)', 'BloombergNEF',
     'Confidential', 'Eurofarma', 'Blizzard Entertainment', 'Yahoo', 'Tableau', 'NPR', 'Under Armour', 'Forbes Brasil',
     'Infor', 'Lear Corporation', 'Azul Linhas A�reas Brasileiras', 'Rio Tinto', 'WEG', 'Bureau Veritas Group',
     'Equinor', 'American Psychological Association', 'GE Aviation', 'McDermott International, Ltd',
     'Rockwell Automation', 'The Home Depot', 'Sandoz', 'XP Investimentos', 'HubSpot', 'MetLife', 'TOTVS',
     'Psychology Today', 'WazaefAlyoum.com - ????? ?????', 'Universal Music Group', 'Landmark Group',
     'Almarai - ???????', 'Vestas', 'JOB VACANCIES TODAY', 'Emerson', 'Fidelity Investments', 'CNBC Make It',
     'TechnipFMC', 'Boston Scientific', 'Patagonia', 'Amdocs', 'Concentrix', 'Jobot', 'Engadget', 'Allergan',
     'Hospital S�rio-Liban�s', 'World Vision', 'Federal Bureau of Investigation (FBI)', 'United States Air Force',
     'Atlas Copco', 'Coty', 'Collabera Inc.', 'British Council', 'Atkins', 'Embraer',
     '????? ???????? | Saudi Employment', 'Repsol', 'Merrill Lynch', 'Zurich Insurance Company Ltd', 'Tetra Pak', 'G4S',
     'Raytheon', 'US Navy', 'Ach� Laborat�rios', 'Palo Alto Networks', 'Biogen', 'Stc', 'Bulgari', 'Odebrecht',
     'Pixar Animation Studios', 'ESPN', 'Aviation Week Network', 'Honda Brasil', 'PlayStation', 'AkzoNobel', 'Arup',
     'BD', 'Tiffany & Co.', 'International Air Transport Association (IATA)', 'Air Liquide', 'Arcadis', 'NetApp',
     'Quartz', 'Novonor', 'Skanska', 'Bradesco Seguros', 'Page Personnel', 'Cencosud S.A.', 'Autodesk', 'Alshaya Group',
     'NASA Jet Propulsion Laboratory', 'Cummins Inc.', 'Mercedes-Benz USA', 'ENGINEERING', 'TD', 'Willis Towers Watson',
     'Kotak Mahindra Bank', 'Texas Instruments', 'Workday', 'C6 Bank', 'Noon', 'Pirelli', 'Anheuser-Busch InBev',
     'Shangri-La Group', 'MRV', 'GitLab', 'Emerson Automation Solutions', 'Royal Caribbean Group', 'NOV',
     'Discovery Inc', 'Grab', 'Zoho', 'Juniper Networks', 'CSC', 'Alibaba.com', 'Brooksource', 'United Airlines', 'WWF',
     'Braskem', 'Mercer', 'U.S. Department of State', 'The Ritz-Carlton Hotel Company, L.L.C.', 'Istoe Dinheiro',
     'Levi Strauss & Co.', 'Salt', 'CVS Health', 'Mercedes-Benz Maybach Fans', 'Fortinet', "Lowe's Companies, Inc.",
     'EPAM Systems', 'Genentech', 'Michelin', 'Chubb', 'Inter-American Development Bank', 'Beiersdorf', 'Suzano',
     'Alicorp', 'Michael Kors', 'Volvo Cars', 'Dassault Syst�mes', 'Leo Burnett', 'HuffPost', 'VICE Media', 'Experis',
     'Flex', 'Riot Games', 'American Heart Association', 'Expedia Group', 'WarnerMedia', 'Motion Recruitment',
     'Cleveland Clinic', 'Andrade Gutierrez S.A.', 'Pernod Ricard', 'Automotive News', 'Whole Foods Market',
     'Capital One', 'ASOS.com', 'Google Ads', 'Atlassian', 'CFA Institute', 'General Mills', 'TEKsystems', 'Variety',
     'Divulga Vagas', 'CNN Brasil', 'Aerotek', 'RBC', 'ArcelorMittal Brasil', 'Digiday', 'B2W Digital',
     'Agilent Technologies', 'Insight Global', 'Blackstone', 'DreamWorks Animation', 'IDEO', 'Thyssenkrupp',
     'Warner Music Group', 'Bunge', 'Global Empregos Ltda', 'IFC - International Finance Corporation', 'USIMINAS',
     'CIB Egypt', 'BT', 'Booz Allen Hamilton', 'Barrick Gold Corporation', 'Empresa Confidencial', 'Southwest Airlines',
     'Starwood Hotels & Resorts Worldwide, Inc.', 'Free Online Courses', 'ABA Journal', 'Cielo', 'Fiverr',
     'Orange Business Services', 'Curriculum.com.br', 'International Monetary Fund',
     'Mr Preventive : Maintenance and Safety News', 'The Business of Fashion', 'ASUS', 'Fujitsu', 'DMCG Global',
     'Localiza', 'PodCast-> The Brutal Truth about Sales & Selling PodCast - on all your favorite PodCast Players',
     'FDA', "Macy's", 'EBay', 'HCA Healthcare', 'Claro Brasil', 'Pinterest', 'Pratt & Whitney', 'Nestl� Nespresso SA',
     'Consolidated Contractors International Company', 'Cond� Nast', 'ServiceNow', 'Citrix', 'Sales Humor',
     'The Goodyear Tire & Rubber Company', 'Jobs In UAE', 'Ajilon', 'Comcast', 'International Rescue Committee',
     'Skift', 'Indeed.com', 'L3Harris Technologies', 'EgyRec-jobs ????? ?? ???', 'DoorDash', 'Statoil',
     'XPO Logistics, Inc.', 'Adobe Creative Cloud', 'Dasa', 'Magna International', 'Volkswagen do Brasil', 'Occidental',
     'Meli� Hotels International', 'Live Nation Entertainment', 'Walt Disney Animation Studios',
     'Turner Construction Company', 'KBR, Inc.', 'Nordstrom', 'Paramount Pictures', 'Amec Foster Wheeler', 'Globant',
     'Parker and Lynch', 'Luxoft', 'Disney General Entertainment Content', 'U.S. Department of Homeland Security',
     'Toyota do Brasil', 'Nokia for service providers', 'T-Mobile', 'Kering', 'Cardinal Health', 'UST',
     'LinkedIn Sales Solutions', 'RecruitingBlogs.com', 'Est�gio Online', 'Monsanto Company', 'Creative Circle',
     'Saatchi & Saatchi', '????? ?? ???', 'National Association of REALTORS�', 'Kantar', 'B3', 'Mott MacDonald',
     'Walgreens', 'Duratex', 'Alcon', 'Africa Confidential', 'NEOM', 'GlobalLogic', 'Sandvik', 'Mphasis', 'Bacardi',
     'BairesDev', 'Gupy', 'Motorola Mobility (a Lenovo Company)', 'Tata Communications', 'Aurora', 'DeepLearning.AI',
     'Inetum', 'Dentsu international', 'Best Quotes of the Day', 'LIBBS FARMAC�UTICA LTDA', 'PRA Health Sciences',
     'Oliver Wyman', 'Mylan', 'Inside Higher Ed', 'Human Resources Development Fund - HRDF - KSA', 'Pakistan Jobs',
     "Rede D'Or S�o Luiz", 'VMLY&R', 'Epic', 'NHS', 'Qatar Jobs - Verified', 'Edelman', 'TASC Outsourcing',
     'Public Investment Fund (PIF)', 'Bimbo do Brasil', 'Azadea Group', 'Civil Engineer', 'Docker, Inc',
     'LinkedIn for Small Business', 'Microsoft Cloud', 'Hospital Alem�o Oswaldo Cruz', 'Marisa S.A.', 'Gilead Sciences',
     'Pearson', 'Best Buy', 'Optello', 'Federal Aviation Administration', 'ScienceDaily',
     'Hire Rightt - Executive Search', 'Benefit Cosmetics', 'Parsons Corporation', 'Viacom', 'DAMAC Properties',
     'Symantec', 'Thoughtworks', 'KEO International Consultants', 'The Nature Conservancy', 'NXP Semiconductors',
     'Elsevier', 'SONDA', 'Caixa Econ�mica Federal', 'CallApp', 'Mechanical Engineering World', 'Fiserv', 'Appen',
     'Grupo Fleury', 'Electrolux', 'Costco Wholesale', 'Aquent', 'FIS', 'Saint Laurent', 'Wazaayf.com',
     'Tata Technologies', 'Oil And Gas Career', 'Yara International', 'Center for Creative Leadership',
     'Grant Thornton LLP (US)', 'Glenmark Pharmaceuticals', 'Macquarie Group', 'Pantone', 'Calvin Klein',
     'VF Corporation', '????? ?? ???? ????????', 'Marsh', 'Catho', 'Barilla Group', 'TIM Brasil', 'Traveloka',
     'Freshworks', 'Shiseido', 'The Chronicle of Higher Education', 'Sheraton Hotels & Resorts', 'PicPay', 'Petroplan',
     'Lendlease', 'Nintendo', 'Ecolab', 'Vigor', 'EMS', 'Alpargatas S.A.', 'Vogue', 'Splunk', 'Smith+Nephew', 'CH2M',
     'Publicis Sapient', 'MongoDB', 'Gap Inc.', 'Votorantim S.A.', 'OECD - OCDE', 'Loggi', 'Addison Group',
     'QuintoAndar', 'Forever 21', 'O Segredo', 'Banco PAN', 'Unity', 'Qatar Foundation', 'Business Insurance',
     'Richemont', 'Intuit', 'Collins Aerospace', 'FireEye, Inc.', 'Tommy Hilfiger', 'State Farm �', 'Sequoia Capital',
     'Hypera', 'Sage', 'Conscience VC', 'The We Company', 'Kiewit', 'Foster + Partners', 'HackerEarth', 'BNY Mellon',
     'Honeywell Aerospace', 'Biosev', 'KUKA', 'None', 'Defense News', 'State Street', 'Neon', 'Rockstar Games',
     'Versace', "Victoria's Secret", 'Stefanini Brasil', 'Belcorp', 'Optum', 'CARE', 'BBC Studios',
     'United Nations Population Fund (UNFPA)', 'Persistent Systems', 'Piracanjuba', 'Alelo Brasil', 'Cia. Hering',
     'The North Face, a VF Company', 'Hill International, Inc.', 'Capgemini Invent', 'Human Rights Watch', 'TUI',
     'Coca-Cola HBC', 'NTT DATA Services', 'Centers for Medicare & Medicaid Services', 'Accenture Brasil', 'Inman News',
     'IDEMIA', 'Spencer Ogden', 'New York Post', 'Lucasfilm', 'GE Capital', 'Perfetti Van Melle', 'Bosch Brasil',
     'Blue Lives Matter', 'Petroleum Development Oman', 'Catraca Livre', 'Aetna, a CVS Health Company', 'The Verge',
     'McCann Worldgroup', 'Huxley', 'BTG Pactual', 'Bons Fluidos', 'Stripe', 'GEODIS', 'TE Connectivity',
     'Tiger Brands', 'Turner & Townsend', 'McKesson', 'Elm Company', 'Unimed', '????? ???????? ksa jobs',
     'NCR Corporation', 'Keller Williams Realty, Inc.', 'Micron Technology', 'Construtora Queiroz Galv�o Brasil',
     'Daraz', 'Clarins', 'QNB Group', 'Gensler', 'BrMalls', 'Shopzu.com', 'Corteva Agriscience', 'Burger King',
     'Solar Coca-Cola', '21st Century Fox', 'American Nurses Association', 'EF Education First', 'Swiss Re', 'WWD',
     'Bath & Body Works', 'Samsung Electronics America', 'Biolab Sanus Farmac�utica', 'Hilti Group', '10 Minute School',
     'Sutherland', 'Pernambucanas', 'Fractal', 'Dropbox', 'Manpower Espa�a', 'Inbound Logistics', 'Experian', 'Zoom',
     'Hitachi Vantara', 'Square', 'Vans, a VF Company', 'Aramex', 'SBM Offshore', 'Hapag-Lloyd AG',
     'M�decins Sans Fronti�res (MSF)', 'Sherwin-Williams', 'Hiring Our Heroes', 'HUGO BOSS', 'Seadrill', 'Sprint',
     'Epsilon', 'Rabobank', 'PPD', 'Job | ?????', 'Empresas Randon', 'Mattel, Inc.', 'Zycus', 'DISYS', 'VentureBeat',
     'Nutanix', 'Snowflake', 'KONE', 'Hootsuite', 'DOLCE&GABBANA S.r.l', 'NielsenIQ', 'Delhivery', 'DSM', 'FARFETCH',
     'Reebok', 'Synechron', 'Strategy&', 'Verizon Business', 'Avaya', 'Trabajo S� Hay', 'Sony Electronics', 'EDP',
     'VLI Log�stica', 'US Tech Solutions', 'Western Digital', '????? ????? ?? ????????', 'The Walt Disney Studios',
     'Smiles', 'Airswift', 'U.S. Bank', 'HARMAN International', 'SC Johnson', 'Mercedes-Benz do Brasil Ltda.',
     'Maersk Oil', 'Microsoft 365', 'USA TODAY', 'Dimension Data', 'WRS - Worldwide Recruitment Solutions',
     'Epic Games', 'Virtusa', 'IEEE', 'National Basketball Association (NBA)', 'Coinbase', 'USAJOBS',
     'Bank of America Merrill Lynch', 'Orascom Construction PLC', 'Bdjobs.com', 'Conduent', 'Cigna', 'Oi',
     'Banco Original', 'Kearney', 'Linde', 'Ingram Micro', "Offre d'emploi", 'Planet Pharma', 'Mobily', 'GroupM',
     'Eliassen Group', 'Groupon', 'Renault', 'Randstad USA', 'Chase', 'PVH Corp.', 'Burger King do Brasil',
     'Synopsys Inc', 'Fircroft', 'Tripadvisor', 'United Nations OCHA', 'National Football League (NFL)', 'Ulta Beauty',
     'Marriott Hotels', 'SAIC', 'ALEXBANK', 'Sura', 'ANBIMA', 'Marathon Oil Corporation', 'Grameenphone Ltd',
     'Boston Dynamics', 'K2 Partnering Solutions', 'MRS Log�stica S.A.', 'Nomura', 'Confidential', 'MAHLE', 'Hulu',
     'Bosch USA', 'ADM', 'BuzzFeed', 'PPG', 'Baker McKenzie', 'Kroger', 'UNOPS', 'PENTOZ', 'CareerUp, Inc.',
     'American Red Cross', 'Thales Digital Security and Identity (ex Gemalto)', 'Liberty Mutual Insurance',
     'IBM Consulting', 'Travelers', 'Parexel', 'J. Walter Thompson Worldwide', 'Zensar Technologies', 'CA Technologies',
     'U.S. Department of Health and Human Services (HHS)', 'Motorola Solutions', 'Carrier HVAC', 'Adecco Middle East',
     'ZDNet', 'Al Rajhi Bank', 'Banco Central do Brasil', 'Google Analytics products', 'Covance', 'KPMG Brazil',
     'TIVIT', 'Humana', 'Activision', 'Z� Delivery', 'Avanade', 'Jobs For U', 'The National Institutes of Health',
     'Grupo Edson Queiroz', 'Delphi', 'Google Workspace', 'IgniteTech', 'The International Civil Aviation Organization',
     'Oil and Gas', 'Cameron, a Schlumberger company', 'XP Inc.', 'Labcorp Drug Development', 'Duolingo',
     'Zimmer Biomet', 'Kaggle', 'Banco BV', 'NetSuite', 'JavaScript Developer', 'SAUDI AIRLINES',
     'Hyundai Motor Brasil', 'Twitch', 'Realtor.com', 'Chemical Engineering World', 'M. Dias Branco', 'Fox News Media',
     'CompTIA', 'International Paper', 'USAA', 'Dar', 'Revlon Inc.', 'Serco', 'Hudson RPO',
     'Stanley Black & Decker, Inc.', 'BRAC', 'ZS', 'Pandora', 'Gameloft', 'Alcoa', 'African Development Bank Group',
     'PCL Construction', 'Kerry', 'Launchmaps', 'Christian Louboutin', 'Lupin', 'Leonardo', 'L3 Technologies',
     'Toyota North America', 'FICO', 'Regeneron', 'Talabat', 'W�rtsil�', 'Oceaneering', 'Khatib & Alami',
     'Bose Corporation', 'Havas Media Group', 'ASML', "Becker's Healthcare", '24 Seven Talent', 'Arm', 'Newell Brands',
     'FEMA', 'Planetizen', 'Microsoft Learn', 'Olam', 'Jabil', 'Toptal', 'Marilan Alimentos S/A', 'Havas',
     '????? ?????', 'Qatar Jobs - Current Vacancies', '3 Cora��es S/A', 'HireMilitary', 'BBDO Worldwide',
     'Techint Engineering & Construction', 'Etisalat Misr', 'CPG Click Petr�leo e G�s', 'Arezzo&Co', 'New Balance',
     'Infineon Technologies', 'Lucas Group', 'Sanofi Genzyme', 'Grupo People RH', 'ERE', 'Nasdaq', 'Intertek',
     'Broadcom Inc.', 'Firmenich', 'Avery Dennison', 'Itau BBA', '??? ?????? | Bank Albilad', 'CENTAURO', 'NVIDIA AI',
     'Asian Paints', 'Mindshare', 'PagSeguro PagBank', '99', 'Binance', 'Senac', 'Agoda', 'Bank of America Business',
     'Tenaris', 'Maldives Jobs', 'Eskom Holdings SOC Ltd', 'Unisys', '????? ???????? | Saudi Jobs',
     'Heidrick & Struggles', 'Mozilla', 'Companhia Sider�rgica Nacional', 'Cinepolis Corporativo', 'ACWA Power',
     'Hyatt Regency', 'Cisco Secure', 'Sophos', 'Rappi', 'Airbus Defence and Space', 'Offensive Security', 'Allstate',
     'Snap Inc.', 'Philips Lighting', 'Coach', 'US Environmental Protection Agency (EPA)', 'Investec', 'Illumina',
     'Banque Misr', 'CAPES - Coordena��o de Aperfei�oamento de Pessoal de N�vel Superior', 'Simplilearn',
     'Iron Mountain', 'Disney Parks, Experiences and Products', 'Anadarko Petroleum Corporation', 'YouGov', 'Rivian',
     'The Metropolitan Museum of Art', 'DDB', '??? ????? ??', 'Havan', 'DeVere Group',
     'Turner (Turner Broadcasting System, Inc)', 'Lionsgate', 'Aviation Recruiting', 'Construtora Tenda',
     'Arabian Construction Co.', 'Cypress HCM', 'The Red Sea Development Company', 'Teradata', 'ERecruiter',
     'Marsh McLennan', 'J.P. Morgan Asset Management', 'Even', 'Getnet Brasil', 'Kroton', 'Lumen Technologies',
     'SulAmerica Saude', 'Petz', 'Nagarro', 'Nexa Resources', 'B. Braun Group', '�rsted', 'Camil Alimentos S/A',
     '??????? - Korsatk', 'ELSEWEDY ELECTRIC', 'Equinix', 'Applied Materials', 'Salvatore Ferragamo', 'Foodpanda',
     'Cerner Corporation', 'Leidos', 'Grupo NotreDame Interm�dica', 'Celgene', 'Selby Jennings', 'The Hershey Company',
     'Aviationjobs.me', 'The Hacker News', 'Sprinklr', 'Robi Axiata Limited', 'Sadara Chemical Company', 'GOLD FIELDS',
     'Hospital S�o Camilo SP', 'Hydrogen Group', 'UiPath', 'Postman', 'Careem', 'Danfoss', 'AngloGold Ashanti',
     'Solomon Page', 'Essilor Group', 'Databricks', 'MonshaatSA', 'TSMC', 'Progressive Recruitment', 'Parker Hannifin',
     'Dyson', 'Media.Monks', 'Airbus Helicopters', 'Avianca Brasil', 'Rigzone', 'Chick-fil-A Corporate Support Center',
     'Reed', 'Vanguard', 'United States Postal Service', 'Anheuser-Busch', 'WTS Energy', 'Carnival Cruise Line',
     'Hire Heroes USA', 'Hess Corporation', 'Privalia', 'PIMCO', 'Sogeti', 'Anthem, Inc.', 'PTC', 'Syneos Health',
     'Zoetis Inc.', 'Amil', 'Herbalife Nutrition', 'DeepMind', 'LinkedIn for Creators',
     'Kopenhagen e Chocolates Brasil Cacau (Grupo CRM)', 'McAfee', 'Canva', 'BMO Financial Group',
     'Data Science Academy', 'NTT Ltd.', 'Cimed Industria De Medicamentos', 'ITC Infotech', 'ENGIE Brasil',
     'Estagi�rios.com', 'Rekrute.com', 'NBC News', 'Smurfit Kappa', 'Joint Commission', 'Figma', 'Cyrela',
     'Veeam Software', 'E3melBusiness academy - ???????? ???? ?????', 'Northern Trust Corporation',
     'Google Developers Experts', 'Portal Vagas - Vagas de Emprego em Fortaleza by Tales Ara�jo', 'J.Crew',
     'Northwestern Mutual', 'AGCO Corporation', 'GHD', 'Universal Pictures', 'Pegasystems', 'Banco Fibra', 'EXL',
     '????? ???', 'Agility', 'Prysmian Group', 'CPFL Energia', 'Prudential Financial', 'Interior Design Magazine',
     'Brookfield Asset Management', 'F5', 'The Judge Group', 'Orange Egypt', 'Norwegian Cruise Line Holdings Ltd.',
     'Aurecon', 'Johns Hopkins Medicine', 'Private Company', 'Lyft', 'Esri', 'Jimmy Choo', 'Talent',
     'Mechanical Engineering Learn', 'Atento', 'Bio-Rad Laboratories', 'Arla Foods',
     'American Honda Motor Company, Inc.', 'MathWorks', 'Hasbro', 'JSL S.A.', 'Harnham', 'A.C.Camargo Cancer Center',
     'MediaCom', 'Ipiranga', 'Neoenergia', 'Zendesk', 'American Marketing Association', 'Arab Bank',
     'International SOS', 'Oxford University Press', 'Penguin Random House', 'EVA pharma', 'Calzedonia Group',
     'DocuSign', 'World Wildlife Fund', 'Kaspersky', 'Summer training & Jobs',
     'Ministry of Human Resources and Social Development - KSA', 'Volt', 'Gulfstream Aerospace', 'Hassan Allam Holding',
     'BP - A Benefic�ncia Portuguesa de S�o Paulo', 'Chlo�', 'Pronaca', 'AppleOne Employment Services',
     'Duke Energy Corporation', 'Ticket', 'Dunnhumby', 'Serasa Experian', 'Medley Ind�stria Farmac�utica',
     'Neuroscience News', 'UPS Supply Chain Solutions', 'CHEP', 'Regus', 'BD Jobs Careers', 'Rothschild & Co',
     'Danish Refugee Council / Dansk Flygtningehj�lp', 'HRCI', 'Cloudflare', 'SOLIDWORKS', 'US Foods',
     'JACOBS DOUWE EGBERTS', 'NIO', 'United Technologies', 'Newmont Corporation', 'Riyad Bank',
     'Google Marketing Platform', 'Vivara', 'Wieden + Kennedy', 'Data Science Central',
     'Uni�o Qu�mica Farmac�utica Nacional', 'Urban Outfitters', 'UL', 'Abril', 'Expleo Group', 'Qatargas', 'Club Med',
     'Esko', 'Minist�rio da Sa�de', 'General Dynamics', 'CrowdStrike', 'Vaco', 'CA Global Africa Recruitment',
     'Sitel Group', 'Russell Tobin', 'KKR & Co. Inc.', 'Facebook AI', 'The TJX Companies, Inc.', 'Expeditors',
     'DOHA BANK', 'Moderna', 'WhiteHat Jr', 'La Repubblica', 'World Wide Technology', 'Seara Alimentos LTDA',
     'Guaranty Trust', 'SWAROVSKI', 'Grupo Selpe', 'Raytheon Technologies', 'Scrum.org', 'Major League Baseball',
     'Bridgestone Americas', 'Banco Bmg', 'Forrester', 'Devon Energy', 'Hays Executive', 'Bollor� Logistics',
     'National Security Agency', 'Liebherr Group', 'Unreal Engine', 'Siemens Digital Industries Software', 'Bauducco',
     'Pierre Fabre Group', 'CELINE', 'SBT', 'Danaher Corporation', 'Saraiva', 'Lionbridge', 'HOK',
     'Zakat, Tax and Customs Authority', 'Freelancer', 'Dafiti', 'TRS Staffing Solutions', 'MSC Cruises', 'BLUE ORIGIN',
     'Architectural Digest', 'Otis Elevator Co.', 'UNIQLO', 'Sysco', 'Manchester United', 'LHH',
     'Honeywell Process Solutions', '????? ?? ??????', 'BDF NIVEA BRASIL', 'Coursera Course Certificates',
     'UX Collective', 'GfK', 'Grupo Petr�polis', 'IHS Markit', 'Weber Shandwick', 'New York Life Insurance Company',
     'Novartis Oncology', 'Technicolor', 'Deloitte Digital', '????? | ?? ?????', 'Air Products', 'JCPenney',
     'BESTSELLER', 'HelloFresh', 'Sonatrach', 'GE Digital', 'Qiddiya | ??????', 'ICON plc', 'Sun Life', 'Pentagram',
     'Pakistan Placement', 'Tech Data', 'Ajinomoto do Brasil Industria e Com�rcio de Alimentos Ltda.',
     'Yoh, A Day & Zimmermann Company', 'Abercrombie & Fitch Co.', 'Embratel', 'Microchip Technology Inc.',
     'National Institute of Mental Health (NIMH)', 'Guerlain', 'Insight', 'Banglalink', 'REI', 'Deloitte Consulting',
     'CB&I', 'Recrutalentos', 'The Green Recruitment Company', 'Cr�dit Agricole CIB', 'Alfa Laval', 'AFRY', 'Zain',
     'R/GA', 'BorgWarner Inc.', 'The Associated Press', 'Volt - International', 'Euromonitor International',
     'Societe Generale Corporate and Investment Banking - SGCIB', 'Huda Beauty', 'Harley-Davidson Motor Company',
     'Saudi Electricity Company', 'Opus Recruitment Solutions', 'Bayt.com', 'International Flavors & Fragrances',
     'Young & Rubicam', 'Hcor', 'Grupo Netshoes', 'RGP', 'Subway', 'Temenos', 'Atento Brasil', 'Black & Veatch', 'OMA',
     'Wayfair', 'SUEZ - Water Technologies & Solutions', 'Peloton Interactive', 'Scrum Alliance', 'Tegra Incorporadora',
     'Alfanar', 'Metso', 'CenturyLink', 'Aramark', 'Publicis', 'GRUNDFOS', 'Protiviti', 'Creditas', 'Rx Technology',
     'Tokio Marine Seguradora', 'McCormick & Company', 'SolarCity', 'Kforce Inc', 'MUFG', 'Quest Diagnostics',
     'SDAIA | ?????', 'Analog Devices', 'Concremat Engenharia e Tecnologia', 'EarthStream Global', 'Charles Schwab',
     'Apsen Farmac�utica', 'Saudi Authority for Industrial Cities and Technology Zones', 'Cvent', 'GQR Global Markets',
     'AWS Training & Certification', 'Marvel Entertainment', 'LexisNexis', 'QuEST Global',
     'Marathon Petroleum Corporation', 'Tirolez', 'Pure Storage', 'BMC Software', 'RICS', 'Spencer Stuart', 'PNC',
     'WGSN', 'Drogaria S�o Paulo S.A', 'MAC Cosmetics', 'Xilinx', 'JetBrains', 'Arab African International Bank',
     'Grey Group', 'Novo Tempo Consultoria e Recursos Humanos Ltda', 'Career Advancers', 'Flowserve Corporation',
     'Apache Corporation', 'Nestl� Waters', 'CCR S.A.', 'Astellas Pharma US', 'Asda', 'Cadence Design Systems',
     'Naughty Dog', 'Schaeffler', 'Enterprise', 'Zebra Technologies', 'Converse', 'Tectra Recrutement Maroc',
     'Al Jazeera Media Network', 'Frog', 'MODEC, Inc.', 'Canadian Solar Inc.', 'Public Health England', 'Sears',
     'FLSmidth', 'Eataly', 'Kavak.com', 'Elastic', 'IMG', 'ZALORA Group', 'Jefferies', 'For6a for jobs', 'ValueLabs',
     'Clifford Chance', 'Gap', 'Yp�', 'IGT Solutions', 'Convergys', 'Xero', 'Cosan', 'UK Health Security Agency',
     'Nextel Brasil', 'Council on Foreign Relations', 'Saks Fifth Avenue', 'BioM�rieux', 'Pif Paf Alimentos', 'Sweco',
     '500 Global', 'Newcrest Mining', 'Cisco Networking', 'Alerte Job', 'S&P Global Market Intelligence', 'RE/MAX',
     'Hill+Knowlton Strategies', 'Neiman Marcus Group', 'We Are Social', 'Pizza Hut', 'Western Union', 'Minerva Foods',
     'American Society of Civil Engineers', 'Lynda.com', 'ITC Hotels', "Domino's", 'Munich Re', 'The Fini Company BR',
     'DLA Piper', 'Headspace Inc.', 'Dr�ger', 'Schindler Group', 'National Park Service',
     'Alexion Pharmaceuticals, Inc.', 'Job Hunt Qatar', 'Starcom', 'McCain Foods', 'Beckman Coulter Diagnostics',
     'C.H. Robinson', 'Algar Telecom', 'Algar Tech', 'Tarte Cosmetics', 'Optimus Search', 'Akamai Technologies',
     'Foxconn', 'Emploitic.com', 'The Carlyle Group', 'Camargo Corr�a Infra', 'Microsoft Visual Studio',
     'Makro Atacadista', 'Falconi', 'Tenneco', 'Gafisa', 'Tyson Foods', 'GLG', 'Waste Management', 'Informatica',
     'Fugro', 'Ettain group', 'S&P Global', 'SKY Brasil', 'Bonatti', 'Automation Anywhere', 'DIRECTV Latin America',
     'OnlineJobs.PH', 'Virgin Galactic', 'Infobip', 'RISMedia', 'Administradores.com', 'TK Elevator', 'Yanbal', 'Lonza',
     'IBM Data and AI', 'AICPA', 'Grupo Tigre', 'Andreessen Horowitz', 'U.S. Secret Service',
     'American Psychiatric Association', 'Bitcoin Inc.', 'First Data Corporation', 'Cloudera', "Kohl's", 'Spectrum',
     'L Brands', 'Atlas Professionals', 'FEBRABAN', 'National Bank of Kuwait', 'OSM Maritime Group', 'Mercy Corps',
     'RD', 'Grupo Protege', 'Paladin', 'World Bank Group', 'Franklin Templeton', 'Confluent', 'Free courses & books',
     'Green Key Resources', 'Diebold Nixdorf', 'Seagate Technology', 'Santa Helena Ind�stria de Alimentos S/A',
     'Valero Energy Corporation', 'Beam Suntory', 'Allen & Overy', 'Arrow Electronics', 'Synergy Interactive',
     'Wounded Warrior Project', 'Perkins&Will', 'Energisa', 'Ambev Tech', 'Telecom Egypt', 'BIC', 'VOC� RH',
     'Soulan Recursos Humanos', 'Divulga Empregos', 'Sabre Corporation', 'U.N.A.M. facultad de ingenieria', 'Garena',
     'Yokogawa', 'Ripple', 'Accenture Strategy', 'Toastmasters International', 'Hospital 9 de Julho', 'Yext', 'HELLA',
     'The Clorox Company', 'OpenText', 'Bupa', 'TransUnion', 'IDC', 'Engineering Consultants Group S.A.', 'CWT',
     'Galderma', 'MediaTek', 'SANS Institute', 'Gulf Connexions Executive Search', 'JCB',
     'CAF - banco de desarrollo de Am�rica Latina', 'Varian', 'Better', 'Thrive Global', 'The Motley Fool', 'Onsemi',
     'Blau Farmac�utica', 'Covidien (Medtronic Minimally Invasive Therapies Group)', 'THG', 'FHI 360', 'Canon EMEA',
     'Brown-Forman', 'Nationwide', 'Disney Cruise Line', "Sam's Club",
     'Canada Revenue Agency - Agence du revenu du Canada', 'NI (National Instruments)', 'Porsche Cars North America',
     'Receita Federal', 'Nordea', 'Defense Intelligence Agency', 'Aptiv', 'Wildlife Conservation Society',
     'Amazon Science', 'Marvell Technology', 'KeepTruckin', 'Skidmore, Owings & Merrill (SOM)',
     '???? ?????? ??????? ???????', 'Edward Jones', 'Amcor', 'Amaris Consulting', 'White Martins', 'ELLE Magazine',
     'KLA', 'Cyient', 'Valve corporation', 'Ame Digital', 'Hiring', 'Marc Jacobs', 'Semrush',
     'Beacon Hill Staffing Group', 'Samarco', 'Hotmart', 'IBM Cloud', '????? ?? ????????', 'Liq', 'Artnet',
     'Publicis Media', 'Pentair', 'NOMAC', 'Saudi Railway Company', 'Logitech', 'Fitch Ratings',
     'Santander Universidades - Brasil', 'Golder', 'PwC Acceleration Centers', 'Revista Manuten��o', 'Noble Drilling',
     'NIIT Limited', 'Alghanim Industries', 'Riovagas', 'Zalando', 'Refinery29, Inc.', 'Mary Kay Global',
     'Teachers Pay Teachers', 'Razorfish', 'Okta', 'TheWrap', 'COFCO International', 'G1', 'Rackspace Technology',
     'Qlik', 'Perficient', 'Kering Eyewear', 'NYSE', 'Fannie Mae', 'Golden VAGAS', 'Arcor do Brasil',
     'Edwards Lifesciences', 'DynCorp International', 'The Museum of Modern Art', 'Planet Technology',
     'CPP Investments | Investissements RPC', 'Argyll Scott', 'Gomes da Costa (Calvo Group)', 'IHeartMedia',
     'VietnamWorks', 'MuleSoft', 'Check Point Software Technologies, Ltd.', 'NTPC Limited', 'Uplers', 'Covestro',
     'AT&T Business', 'Essity', 'Ethereum', 'Yum! Brands', 'Manserv', 'TietoEVRY', 'Eneva', 'Robinhood', "Barron's",
     'Canon USA', 'Banque Saudi Fransi', 'Trina Solar', 'HSBC Global Banking and Markets', '????? ?? ???',
     'Lam Research', 'BSI', 'Linx', 'King Faisal Specialist Hospital and Research Centre (Gen. Org.)', 'JAC Group',
     'Ross Stores, Inc.', 'Center for Strategic and International Studies (CSIS)',
     'AfdlJobs.com | ????? ??? ???? ??? ??????', 'Grupo Cia de Talentos', 'VagasEmbarcado', 'Towards AI',
     'FMC Technologies', 'Marine Corps Recruiting', 'Grupo Marista', 'Ternium', 'Tetra Tech', 'LANXESS', 'MSCI Inc.',
     'Securitas Security Services USA, Inc.', 'Gallagher', 'Vertex Pharmaceuticals',
     'URS Corporation, An AECOM Company', 'Morgan Stanley Wealth Management', 'EC-Council',
     'The American Institute of Architects (AIA)', 'Jobzella', 'MarketWatch', 'Dollar General', 'Laborat�rio Teuto',
     'Emerson Network Power', 'Fresenius Medical Care North America', 'Lucid Motors', 'Columbia Sportswear Company',
     'Steelcase', 'Sotreq S/A', 'Reuters', 'JetBlue', 'Mammoet', 'Oxiteno', 'Le�o Alimentos e Bebidas', 'GKN Aerospace',
     'Oman Air', 'Rumo', 'Caderno Nacional', 'Solenis', 'American Cancer Society', 'Veterans Employment',
     'Alg�rie Telecom', 'Klarna', 'Meta for Business', 'SUCCESS Magazine', 'Arista Networks', 'Atacad�o', 'Trafigura',
     'The Body Shop', 'LinkedIn for Nonprofits', 'Jobtrack Management Services, Dubai, UAE',
     'Black Rifle Coffee Company', 'Ingersoll Rand', 'Amway', 'Trend Micro', 'Morgan Philips Group',
     'Van Cleef & Arpels', 'Mitchell Martin Inc.', 'Omnicom Media Group', 'Ball Corporation', 'Glassdoor', 'V.Group',
     'Russell Reynolds Associates', 'Agi', 'Empreendimentos Pague Menos SA', 'Twilio', 'Digitas North America',
     'Westin Hotels & Resorts', 'Razer Inc.', 'Bridgewater Associates', 'HarperCollins Publishers',
     '????? - ?????? ?????', 'Happy Networking! ????', 'International Coaching Federation', 'Abunayyan Holding',
     'BAE Systems, Inc.', 'HDR', 'Habitat for Humanity International', 'UBS Investment Bank', 'Lorien',
     'MotivationalLines.com', 'Birlasoft', 'Univar Solutions', 'Tecoloco.com', 'Harvey Nash', 'BCD Travel',
     'Department for International Trade (DIT)', 'The Linux Foundation', 'CNBC Events', 'Conagra Brands',
     'Catalent Pharma Solutions', 'UCB', 'Compass', 'Devoteam', 'Acne Studios AB',
     'ASME (The American Society of Mechanical Engineers)', 'Progen', 'DSJ Global', '???? ???????', 'Tok&Stok',
     'GUESS?, Inc.', 'Trane', 'Getty Images', 'InMobi', '(ISC)�', 'SIAC Construction',
     'EEP - Electrical Engineering Portal', 'Swatch Group', 'Reserva', 'Archirodon Group N.V.', 'Xoriant',
     'American Bar Association', 'Solar Turbines', 'GRU Airport - Aeroporto Internacional de S�o Paulo', 'Bitcoin',
     'O Botic�rio', 'In Job', 'Amazon Lab126', "Christie's", 'Ansys', 'NTT DATA', 'Randstad Sourceright',
     'Publix Super Markets', 'National Bank of Egypt (NBE)', 'Ultragaz', 'Morningstar', 'Eurasia Group', 'Andela',
     'Staples', 'Career Opportunity in Bangladesh', 'Genesys', 'Aruba, a Hewlett Packard Enterprise company',
     'BearingPoint', 'Mitsubishi Electric Automation, Inc.', 'Komatsu Construction', 'XTO Energy', 'Elanco',
     'Siemens EDA (Siemens Digital Industries Software)', 'Anthropologie', 'Job Announcement in Bangladesh',
     'A Cloud Guru', 'Internal Revenue Service', 'Syneos Health Clinical Solutions', 'CMPC',
     'Refinitiv, an LSEG business', 'Chemonics International', 'AXA Gulf', 'N26', 'Bentley Systems', 'CVC CORP',
     'Orascom Development Egypt', 'Getir', 'Swissport', 'Grupo Bandeirantes de Comunica��o', 'Mentor Graphics',
     'Alteryx', 'Saudi Aramco Total Refining and Petrochemical Company (SATORP)', 'Farmers Insurance', 'Meet', 'CI&T',
     'ArabJobs.com', 'Cambridge University Press & Assessment', 'Microsoft Dynamics 365', 'Gympass', 'Grupo Pardini',
     'PHD', 'Abu Dhabi Islamic Bank - Egypt', 'RTI International', 'Stealth Startup', 'Capco', 'WhatsApp',
     'DaVita Kidney Care', 'UNRWA', 'Design Milk Co.', 'HERE Technologies', 'Greystar',
     'Substance Abuse and Mental Health Services Administration (SAMHSA)', 'Astek', 'HDI Seguros', 'NEC Corporation',
     'Mercuri Urval', 'Infinity Consulting Solutions', 'Adobe Marketo', 'Grupo Camargo Corr�a', 'Palantir Technologies',
     'Donaldson', 'Tata Elxsi', 'Wunderman Thompson', 'Saudi Credit Bureau - SIMAH', 'Garmin', 'Puratos',
     'Alphabet Inc.', 'Hamad Medical Corporation', 'Phillips 66', 'BM&FBOVESPA', 'Varroc Lighting Systems', 'FDM Group',
     'Autism Speaks', 'AIGA Design', 'Moving Picture Company', 'Jobs Garments/Textiles/Buying And Merchandising',
     'Oakley', 'Machine Learning', 'Teach For America', 'Zynga', 'Zain KSA', 'AMERICAN EAGLE OUTFITTERS INC.', 'Sulzer',
     'Hogan Lovells']

    def start_requests(self, domain=domain, company_list= company_list):
        for i in company_list:
            yield scrapy.Request(url=domain + i,callback = self.parse)


    def parse(self, response):
        link1 = response.xpath("//div[@class ='result']/div/a/@href").extract_first()

        yield {
            "company" : link1
        }
